// ── 304 afirmacji w 8 kategoriach ──────────────────────────────────────────

export type AffirmationCategory =
  | 'love' | 'peace' | 'abundance' | 'protection'
  | 'healing' | 'awakening' | 'confidence' | 'gratitude';

export type Affirmation = {
  id: string;
  text: string;
  category: AffirmationCategory;
};

const love: string[] = [
  'Jestem godna/godny miłości w każdej postaci, jaką przybiera.',
  'Daję i przyjmuję miłość z otwartym sercem i pełną obecnością.',
  'Moje relacje są pełne wzajemnego szacunku i głębokiego zrozumienia.',
  'Otwieram serce na nowe połączenia, zachowując własne centrum.',
  'Kocham siebie tak, jak chciałbym/chciałabym być kochana/kochany przez innych.',
  'Każda relacja w moim życiu wnosi coś cennego i naucza mnie czegoś ważnego.',
  'Jestem otoczona/otoczony ludźmi, którzy wspierają mój wzrost i autentyczność.',
  'Moje serce jest bezpiecznym miejscem — zarówno dla mnie, jak i dla innych.',
  'Przyciągam miłość, która jest dojrzała, spokojna i prawdziwa.',
  'Zasługuję na relacje pełne ciepła, obecności i troski.',
  'Pozwalam sobie kochać i być kochanym/kochaną bez strachu.',
  'Moje granice w relacjach budują most, nie mur.',
  'Wybieram partnerów, którzy widzą moje prawdziwe ja i je cenią.',
  'Miłość do siebie jest fundamentem każdej miłości, jaką mogę dać innym.',
  'Kiedy jestem pełna/pełny miłości do siebie, moje relacje rozkwitają.',
  'Uzdrawiam wzorce relacyjne, które nie służą już mojemu sercu.',
  'Każde pożegnanie uwalnia przestrzeń dla głębszego połączenia.',
  'W moim życiu jest miejsce na intymność, zaufanie i prawdziwą bliskość.',
  'Przyciągam miłość, która inspiruje mnie do bycia lepszą/lepszym wersją siebie.',
  'Kocham swoje serce, które mimo trudności nadal chce się otwierać.',
  'Relacje w moim życiu są moje źródłem siły, nie wyczerpania.',
  'Komunikuję swoje potrzeby jasno i z życzliwością dla obu stron.',
  'Oddaję miłość świadomie i przyjmuję ją z wdzięcznością.',
  'Uzdrawiam z przekonania, że nie zasługuję na trwałą miłość.',
  'Moje serce jest otwarte, chronione i gotowe na prawdziwy związek.',
  'Wybaczam sobie wcześniejsze wzorce w relacjach, które mnie raniły.',
  'Przyciągam przyjaźnie, które są wzajemne, lekkie i prawdziwe.',
  'Znam swoje potrzeby i mam odwagę je artykułować w relacjach.',
  'Jestem gotowa/gotowy na głębszą miłość, niż kiedykolwiek doświadczyłam/em.',
  'Wdzięczna/wdzięczny jestem za każde serce, które dotknęło moje życie.',
  'Moje relacje ewoluują razem ze mną, z szacunkiem i naturalnym rytmem.',
  'Miłość w moim życiu jest lekka jak poranek i trwała jak księżyc.',
  'Pozwalam sobie być widziana/widziany w całości — ze słabościami i siłą.',
  'Moje serce wybacza i uwalnia to, co było — z miłością.',
  'Wnoszę do relacji to, czego nauczyłam/em się z każdej trudności.',
  'Jestem kochana/kochany. Jestem potrzebna/potrzebny. Jestem ważna/ważny.',
  'Przyciągam partnerstwo oparte na wzajemnym wzroście i szacunku.',
  'Moje życie jest wypełnione miłością — do siebie, do innych, do świata.',
];

const peace: string[] = [
  'Moje ciało wie, jak wracać do spokoju — ufam temu procesowi.',
  'Oddech jest moją kotwicą w każdej chwili niepokoju.',
  'Wybieram spokój zamiast reakcji, gdy emocje stają się głośne.',
  'Wewnętrzna cisza jest moim naturalnym stanem — wraca zawsze.',
  'Jestem spokojniejsza/spokojniejszy od wszystkiego, co mnie otacza.',
  'Puszczam kontrolę nad tym, na co nie mam wpływu.',
  'Moje myśli są łagodniejsze niż wczoraj i stają się coraz spokojniejsze.',
  'Wybieram reagować zamiast reagować impulsywnie.',
  'Spokój nie jest brakiem emocji — to zdolność do bycia z nimi bez ucieczki.',
  'Moje nerwy się uspokajają, moje ciało się rozluźnia, mój umysł się wycisza.',
  'Każda chwila, w której wybieram spokój, zmienia mój układ nerwowy.',
  'Jestem bezpieczna/bezpieczny w tej chwili — tu i teraz.',
  'Nie muszę rozwiązywać wszystkiego naraz. Wystarczy jeden mały krok.',
  'Cisza wewnętrzna mówi głośniej niż zewnętrzny hałas.',
  'Wracam do siebie poprzez oddech, ruch i obecność.',
  'Daję sobie zgodę na bycie spokojną/spokojnym, nawet gdy świat nie jest.',
  'Puszczam myśli, które kłócą się z moim wewnętrznym pokojem.',
  'Mój spokój jest prawdziwą siłą, nie ucieczką przed rzeczywistością.',
  'Wybieram otoczenie, które wspiera mój stan wewnętrzny.',
  'Regulacja emocji to umiejętność, którą rozwijam każdego dnia.',
  'Odpoczynek jest produktywny. Cisza jest twórcza. Spokój jest siłą.',
  'Pozwalam sobie na pauzę — bez winy, bez pośpiechu.',
  'Moje ciało zasługuje na odprężenie, mój umysł na ciszę.',
  'Jestem tutaj. Jestem teraz. To wystarczy.',
  'Nawet trudne chwile przechodzą. Jestem większa/większy niż to, co przeżywam.',
  'Mój układ nerwowy uczy się bezpieczeństwa każdego dnia.',
  'Spokój to mój wybór, nawet gdy nie jest moją pierwszą odpowiedzią.',
  'Mam prawo do przerwy, do zatrzymania, do odetchnięcia.',
  'Uwalniając napięcie z ciała, uwalniają się też myśli.',
  'Nie spieszę się z wnioskami ani z decyzjami — jest czas.',
  'Jestem łagodna/łagodny dla siebie w chwilach, gdy jest trudno.',
  'Moje emocje są informacją, nie wyrokiem.',
  'Wybaczam sobie i innym, bo to uwalnia mój własny spokój.',
  'Wewnętrzna harmonia jest możliwa nawet wśród zewnętrznego chaosu.',
  'Dziś jest spokojniejszy dzień, bo ja wybieram spokój.',
  'Prowadzę siebie z cierpliwością — tak jak prowadziłabym/prowadziłbym kogoś, kogo kocham.',
  'Zatrzymuję się i oddycham — wystarczy ten jeden ruch.',
  'Moje życie przepływa z naturalnym rytmem, kiedy nie stawiam mu oporu.',
];

const abundance: string[] = [
  'Zasługuję na obfitość w każdym obszarze swojego życia.',
  'Moje działania tworzą wartość, która wraca do mnie wielokrotnie.',
  'Pieniądze i zasoby przepływają przez moje życie z naturalną łatwością.',
  'Jestem otwarta/otwarty na możliwości, które przynosi każdy nowy dzień.',
  'Mam wystarczająco dużo, jestem wystarczająco dużo, robię wystarczająco dużo.',
  'Obfitość nie jest dla mnie groźna — jest moim naturalnym stanem.',
  'Pracuję ze swoją siłą i przekazuję ją w świat z pewnością siebie.',
  'Moje talenty mają wartość i są potrzebne w tym świecie.',
  'Przyciągam możliwości, które są zgodne z moim najwyższym dobrem.',
  'Moje decyzje finansowe pochodzą z mądrości, nie ze strachu.',
  'Tworzę obfitość świadomie, krok po kroku, z intencją.',
  'Mam prawo do powodzenia i do jego pełnego odczucia.',
  'Uwalniają się ze mnie wszystkie przekonania, że nie zasługuję na sukces.',
  'Jestem otwarta/otwarty na wsparcie, współpracę i dary od innych.',
  'Moje projekty i marzenia mają potencjał, który realizuje się w czasie.',
  'Pozwalam sobie chcieć więcej — bez wstydu i bez przeprosin.',
  'Obfitość to nie egoizm — to energetyczna odpowiedzialność.',
  'Każdy krok, który robię, buduje fundamenty mojej przyszłości.',
  'Ufam, że wszechświat wspiera moje intencje i działania.',
  'Przyciągam zasoby dokładnie wtedy, gdy są mi potrzebne.',
  'Wartość, którą wnoszę do świata, wraca do mnie w sposób, jakiego nie przewiduję.',
  'Prosperuję w tym, co kocham robić.',
  'Jestem twórczynią/twórcą własnej rzeczywistości i wybieram obfitość.',
  'Moje granice chronią moją energię, która napędza mój sukces.',
  'Mam odwagę prosić o to, czego potrzebuję — zarówno od siebie, jak i od świata.',
  'Przyjmuję z wdzięcznością wszystko, co życie mi oferuje.',
  'Moje życie wypełnia się po brzegi tym, co naprawdę jest dla mnie ważne.',
  'Sukces jest procesem, a nie celem — jestem w tym procesie każdego dnia.',
  'Moje potrzeby są zaspokajane. Moje pragnienia mają przestrzeń.',
  'Działam z inspiracji, nie z desperacji, i to przynosi najlepsze efekty.',
  'Mogę i jestem wystarczająco dobra/dobry, by osiągnąć to, czego pragnę.',
  'Każda praca, którą wykonuję z sercem, przynosi mi powroty.',
  'Bogate jest moje życie — w relacje, w doświadczenia, w wolność.',
  'Buduję swoje życie tak, jak chcę, by wyglądało.',
  'Uwalniam się od mentalności niedoboru i witam mentalność obfitości.',
  'Zasługuję na wynagrodzenie adekwatne do swojego wkładu.',
  'Moje życie się rozwija w tempie, które mi służy.',
  'Jestem magnesem dla możliwości, które wspierają mój cel.',
];

const protection: string[] = [
  'Jestem otoczona/otoczony światłem ochronnym, które odpycha to, co nie służy.',
  'Moja energia jest moja i mam prawo jej chronić.',
  'Ustanawiam granice energetyczne z miłością i stanowczością.',
  'Nie przejmuję emocji ani energii, które nie należą do mnie.',
  'Jestem zakorzeniona/zakorzeniony i bezpieczna/bezpieczny w swoim centrum.',
  'Moje granice są jasne, szanowane i wzmacniane każdego dnia.',
  'Zwracam to, co nie jest moje — z miłością i bez winy.',
  'Otaczam się tylko energiami, które mnie wspierają i rozwijają.',
  'Wiem, kiedy powiedzieć nie — i robię to z szacunkiem do siebie.',
  'Moje ciało sygnalizuje mi, kiedy zbliżam się do granic energetycznych.',
  'Chronię swoją przestrzeń — fizyczną, emocjonalną i duchową.',
  'Jestem przezroczysta/przezroczysty dla energii, która mi nie służy.',
  'Moja aura jest czysta, silna i przepełniona własną energią.',
  'Nie muszę brać na siebie bólu innych, żeby im pomóc.',
  'Moje granice są formą miłości — do siebie i do innych.',
  'Odczuwam energię otoczenia i świadomie wybieram, na co się otwieram.',
  'Jestem chroniona/chroniony przez swoją intencję i wewnętrzną siłę.',
  'Wychodzę ze środowisk, które mnie wyczerpują, bez poczucia winy.',
  'Moja przestrzeń domowa jest sanktuarium spokoju i regeneracji.',
  'Wybieram ludzi, miejsca i sytuacje, które mnie wzmacniają.',
  'Moje przekonania i wartości tworzą naturalną tarczę przed tym, co obniża moją wibrację.',
  'Słucham intuicji, która mówi mi, kiedy się wycofać.',
  'Mogę pomagać innym, nie tracąc przy tym siebie.',
  'Moja energetyczna higiena jest tak ważna jak ta fizyczna.',
  'Oczyszczam swoją przestrzeń z wzorców, myśli i relacji, które nie służą.',
  'Jestem silna/silny w swojej własnej energii — nie potrzebuję aprobaty z zewnątrz.',
  'Moja obecność chroni i uzdrawia — ale tylko gdy ja sama/sam jestem całościowa/całościowy.',
  'Wiem, kiedy odejść od rozmowy, sytuacji lub relacji.',
  'Zaczynam każdy dzień od oczyszczenia swojej energii i ustanowienia intencji.',
  'Mam prawo do prywatności swojego wewnętrznego świata.',
  'Nie tłumaczę się ze swoich granic — po prostu je mam i utrzymuję.',
  'Moje "nie" jest pełnym zdaniem, wyrażonym z szacunkiem.',
  'Chronię swój spokój jak najcenniejszy zasób — bo nim jest.',
  'Zwalniam z siebie to, co zostało przejęte nieświadomie od innych.',
  'Odbudowuję swoje zasoby energetyczne każdego dnia przez świadomy odpoczynek.',
  'Jestem bezpieczna/bezpieczny w swoim ciele, w swoim domu, w swoim życiu.',
  'Ufam swojemu instynktowi w kwestiach ochrony swojej energii.',
  'Moja ochrona jest wbudowana w moją świadomość i codzienną praktykę.',
];

const healing: string[] = [
  'Moje ciało zna drogę do zdrowia i podążam za jego mądrością.',
  'Uzdrawiam w swoim własnym tempie — bez porównywania się z innymi.',
  'Każdy dzień jest nową możliwością regeneracji i odnowy.',
  'Pozwalam sobie czuć to, co trudne — to pierwsza warstwa uzdrowienia.',
  'Jestem więcej niż moje rany. Jestem też siłą, która je przeżyła.',
  'Moje ciało i umysł regenerują się podczas snu, odpoczynku i ciszy.',
  'Uwalniają się ze mnie stare bóle, które nie służą już mojemu wzrostowi.',
  'Powoli, ale konsekwentnie — buduję wewnętrzną siłę.',
  'Zasługuję na pomoc, wsparcie i uzdrawiające towarzystwo.',
  'Moje przeżycia mnie ukształtowały, ale nie definiują tego, kim jestem teraz.',
  'Wybaczam sobie to, co zrobiłam/zrobiłem z bólu lub nieświadomości.',
  'Jestem zdolna/zdolny do transformacji — to jest moja największa siła.',
  'Każda emocja, którą poczuję do końca, uwalnia mnie i uzdrawia.',
  'Ciało przechowuje mądrość. Słucham go z ciekawością i szacunkiem.',
  'Uzdrawianie nie jest linią prostą — ale zawsze podążam naprzód.',
  'Pozwalam sobie na nieidealne chwile podczas drogi ku zdrowiu.',
  'Moje nerki, serce i każdy organ pracują na moją korzyść z naturalną mądrością.',
  'Jestem gotowa/gotowy przyjąć pomoc — jako siłę, nie słabość.',
  'Zwalniam napięcie z każdego mięśnia, każdej tkanki, każdej komórki.',
  'Uzdrawianie wzorców rodzinnych to dar dla mnie i dla przyszłych pokoleń.',
  'Każdy rytuał oczyszczenia zbliża mnie do mojego prawdziwego ja.',
  'Jestem na ścieżce, nawet gdy nie widzę jej końca.',
  'Mój układ nerwowy uczy się spokoju, bezpieczeństwa i zaufania.',
  'Uwalniają się ze mnie emocjonalne bloki, które nie służą już mojemu życiu.',
  'Zasługuję na uzdrowienie — głębokie, prawdziwe i trwałe.',
  'Moje zdrowie jest priorytetem — i tak je traktuję.',
  'Jestem silna/silny dzięki temu, przez co przeszłam/przeszedłem.',
  'Powrót do siebie to najpotężniejszy ruch uzdrawiający.',
  'Przyjmuję uzdrowienie na każdym poziomie — fizycznym, emocjonalnym, duchowym.',
  'Moje rany mają głos, który słucham z ciekawością, nie ze strachem.',
  'Uzdrawiam przez obecność, nie przez ucieczkę.',
  'Moje zdrowie psychiczne i fizyczne są równie ważne i równie pielęgnowane.',
  'Daję sobie czas na uzdrowienie, bez pośpiechu i bez presji.',
  'Tworzę warunki, w których moje ciało może się regenerować.',
  'Uzdrowienie jest możliwe — w to wierzę całą sobą.',
  'Każdy krok na ścieżce uzdrowienia jest drobnym zwycięstwem.',
  'Jestem po swojej stronie — zawsze, nawet gdy jest trudno.',
  'Uzdrawiam się poprzez miłość — do siebie i do swojego procesu.',
];

const awakening: string[] = [
  'Jestem istotą duchową przeżywającą ludzkie doświadczenie.',
  'Moje przebudzenie jest procesem, nie wydarzeniem — trwa każdego dnia.',
  'Jestem połączona/połączony z czymś większym niż to, co widzę.',
  'Moja intuicja jest prawdziwym kompasem — ufam jej wskazaniom.',
  'Rozwijam się duchowo każdego dnia, nawet gdy tego nie czuję.',
  'Jestem otwarta/otwarty na nauki, jakie niesie każda sytuacja.',
  'Widzę wzorce w swoim życiu i rozumiem ich duchowy sens.',
  'Łączę się z mądrością mojego wyższego ja.',
  'Moje przebudzenie otwiera mnie na głębszą miłość i szersze rozumienie.',
  'Jestem kanałem czystej, twórczej energii.',
  'Synchroniczności w moim życiu są odpowiedziami na moje pytania.',
  'Żyję z intencją, uważnością i wdzięcznością.',
  'Słucham ciszy między myślami — tam jest mądrość.',
  'Rozpoznaję w każdym człowieku duszę na własnej ścieżce.',
  'Ufam boskiemu planowi, nawet gdy go nie rozumiem.',
  'Moje życie jest szlachetną podróżą duszy, nie przypadkowym błądzeniem.',
  'Jestem uczennią/uczniem życia i wdzięcznie przyjmuję każdą lekcję.',
  'Medytacja, modlitwa i cisza otwierają mnie na wyższe rozumienie.',
  'Widzę sacrum w codzienności — w porannym słońcu, w oddechu, w ciszy.',
  'Mój stan wewnętrzny tworzy zewnętrzną rzeczywistość — dbam o oba.',
  'Jestem coraz bardziej świadoma/świadomy swojego prawdziwego natury.',
  'Moje przebudzenie jest darem dla siebie i dla świata.',
  'Wnoszę więcej światła do przestrzeni, w których przebywam.',
  'Akceptuję to, czego nie rozumiem, ufając, że zostanie mi to wyjaśnione.',
  'Poszukuję prawdy i mam odwagę żyć zgodnie z nią.',
  'Mój duch jest wolny — niezależny od lęków i ograniczeń ego.',
  'Codzienne praktyki duchowe wzmacniają moje połączenie z wyższą świadomością.',
  'Jestem przewodzona/przewodzony przez miłość, nie przez strach.',
  'W moim wnętrzu jest źródło mądrości, które zawsze jest dostępne.',
  'Przebudzam się coraz bardziej — do miłości, do prawdy, do obecności.',
  'Moje życie jest sakralne i każdy dzień jest ceremonią.',
  'Jestem wdzięczna/wdzięczny za tę inkarnację i wszystko, czego mnie uczy.',
  'Widzę Boskość w sobie i w każdej żywej istocie.',
  'Moje przebudzenie jest trwałe — rośnie z każdym świadomym wyborem.',
  'Jestem połączona/połączony ze strumieniem życia, który płynie przeze mnie.',
  'Ufam podróży swojej duszy, nawet gdy nie znam celu.',
  'Codziennie wzbogacam swoje życie duchowe o jeden świadomy moment.',
  'Jestem żywym przykładem tego, że miłość i świadomość są możliwe.',
];

const confidence: string[] = [
  'Ufam sobie — swojemu osądowi, swoim decyzjom, swojej drodze.',
  'Jestem wystarczająco dobra/dobry dokładnie taka/taki, jaka/jaki jestem.',
  'Mój głos ma wartość i warto, żebym go używała/używał.',
  'Staję po swojej stronie — nawet gdy inni tego nie robią.',
  'Moja wartość nie zależy od aprobaty innych.',
  'Jestem odważna/odważny w byciu sobą, w każdej sytuacji i każdej przestrzeni.',
  'Wiem, czego chcę — i idę po to spokojnie i konsekwentnie.',
  'Moje decyzje są mądre, bo pochodzą z głębokiego wewnętrznego rozumienia.',
  'Przeszkody mnie wzmacniają, nie zatrzymują.',
  'Jestem w stanie osiągnąć to, co sobie postawię za cel.',
  'Moje ciało mówi o pewności siebie — staję prosto, mówię jasno.',
  'Nie potrzebuję być doskonałą/doskonałym, żeby być wartościową/wartościowym.',
  'Podejmuję ryzyko, bo wiem, że mogę sobie poradzić z każdym wynikiem.',
  'Jestem dumna/dumny z drogi, którą przeszłam/przeszedłem.',
  'Moje nieidealne próby mają więcej wartości niż nieskończone planowanie.',
  'Uczę się z błędów zamiast siebie za nie karać.',
  'Wiem, że jestem w stanie tego dokonać — nawet gdy nie wiem jeszcze jak.',
  'Moje lęki przed oceną słabną z każdym autentycznym krokiem.',
  'Zasługuję na zajmowanie przestrzeni — w rozmowie, w pracy, w życiu.',
  'Jestem autorką/autorem własnego życia, nie statystką/statystą w opowieści innych.',
  'Zabieram głos, nawet gdy drżę — szczególnie wtedy.',
  'Moje wątpliwości są naturalną częścią procesu, nie dowodem na moją słabość.',
  'Buduję pewność siebie poprzez kolejne małe, odważne ruchy.',
  'Szanuję siebie za to, kim jestem — nie za to, co osiągam.',
  'Mam wystarczająco dużo odwagi na jedno działanie dzisiaj.',
  'Jestem kompetentna/kompetentny, zdolna/zdolny i gotowa/gotowy.',
  'Nie muszę udowadniać swojej wartości — po prostu ją mam.',
  'Wychodzę z komfortu strefy regularnie — i za każdym razem rośnę.',
  'Moje podejście do życia z otwartością i śmiałością przyciąga właściwe możliwości.',
  'Jestem niezawodna/niezawodny dla siebie — dotrzymuję obietnic, jakie daję sobie.',
  'Porównywanie się z innymi zastyga we mnie — skupiam się na własnej ścieżce.',
  'Moja unikalność jest siłą, nie przeszkodą.',
  'Stawiam się na pierwszym miejscu w kwestiach dotyczących mojego życia.',
  'Potrafię poprosić o pomoc — to jest odwaga, nie słabość.',
  'Moje życie jest ciekawym eksperymentem, a ja jestem dzielną/dzielnym eksploratorką/eksploratorem.',
  'Jestem gotowa/gotowy przyjąć komplementy i uznanie z gracją.',
  'Mam prawo do własnego zdania, nawet gdy jest niepopularne.',
  'Każdego dnia staję się odważniejszą/odważniejszym wersją siebie.',
];

const gratitude: string[] = [
  'Jestem głęboko wdzięczna/wdzięczny za to życie, które mi zostało dane.',
  'Dostrzegam piękno w małych rzeczach, które wypełniają mój dzień.',
  'Moje serce jest pełne wdzięczności za każdą lekcję, którą przeżyłam/przeżyłem.',
  'Wdzięczność otwiera mnie na jeszcze więcej dobra w moim życiu.',
  'Jestem wdzięczna/wdzięczny za moje ciało, które każdego dnia dla mnie pracuje.',
  'Dziękuję za relacje, które mnie kształtują i inspirują.',
  'Wdzięczna/wdzięczny jestem za każdy nowy dzień, który jest darem.',
  'Moje "mam" przewyższa moje "chcę" — i z wdzięcznością to dostrzegam.',
  'Doceniam drobne przyjemności życia: ciepłą herbatę, poranek, ciszę.',
  'Wdzięczność zmienia moje spojrzenie na każdą sytuację.',
  'Jestem wdzięczna/wdzięczny za wyzwania, które mnie wzmocniły.',
  'Każdy człowiek w moim życiu jest nauczycielem, za którego dziękuję.',
  'Moje życie jest wypełnione obfitością — widzę ją wszędzie.',
  'Dziękuję za powietrze, za ziemię, za wodę — za to, co codziennie podtrzymuje moje życie.',
  'Wdzięczność jest moją codzienną praktyką i transformującą mocą.',
  'Zauważam, doceniam i nazywam to, co dobre w każdym dniu.',
  'Jestem wdzięczna/wdzięczny za swoje instynkty, które mnie chronią.',
  'Dziękuję za możliwość wzrostu, nauki i stawania się lepszą/lepszym.',
  'Moje serce się rozszerza, gdy zatrzymuję się na wdzięczności.',
  'Jestem wdzięczna/wdzięczny za trudne okresy — przyniosły mi mądrość.',
  'Wdzięczność za przeszłość oczyszcza przestrzeń na przyszłość.',
  'Dziękuję za każdą oddaną mi chwilę ciszy i spokoju.',
  'Wdzięczna/wdzięczny jestem za możliwość bycia na tej ścieżce duchowej.',
  'Dostrzegam cuda w codzienności — synchroniczności, drobne gesty, piękno natury.',
  'Wdzięczność czyni moje życie bogatszym niż jakiekolwiek zewnętrzne zasoby.',
  'Dziękuję za miłość — w każdej formie, w jakiej się przejawia.',
  'Jestem wdzięczna/wdzięczny za siebie — za swoją drogę, charakter i mądrość.',
  'Wdzięczność i strach nie mogą istnieć w tym samym czasie — wybieram wdzięczność.',
  'Każdy wieczór zamykam dziękczynieniem za jeden dar dnia.',
  'Mój dziennik wdzięczności to moje najważniejsze duchowe ćwiczenie.',
  'Dziękuję za zmiany — nawet te trudne — bo przynoszą odnowę.',
  'Jestem wdzięczna/wdzięczny za swoje ciało, swój dom, swoje życie.',
  'Wdzięczność jest energią, która przyciąga więcej tego, za co dziękuję.',
  'Dostrzegam i świętuje małe zwycięstwa każdego dnia.',
  'Dziękuję za spokój, który wypracowuję codziennie od nowa.',
  'Wdzięczna/wdzięczny jestem za wszystko, co mnie tutaj doprowadziło.',
  'Moje życie jest darem — i traktuję go jak taki każdego dnia.',
  'Dziękuję. Za wszystko. Bez wyjątku.',
];

// ── Zbiorczy eksport ───────────────────────────────────────────────────────────

const buildCategory = (texts: string[], cat: AffirmationCategory): Affirmation[] =>
  texts.map((text, i) => ({ id: `${cat}_${i}`, text, category: cat }));

export const PORTAL_AFFIRMATIONS: Affirmation[] = [
  ...buildCategory(love, 'love'),
  ...buildCategory(peace, 'peace'),
  ...buildCategory(abundance, 'abundance'),
  ...buildCategory(protection, 'protection'),
  ...buildCategory(healing, 'healing'),
  ...buildCategory(awakening, 'awakening'),
  ...buildCategory(confidence, 'confidence'),
  ...buildCategory(gratitude, 'gratitude'),
];

/** Deterministyczny wybór afirmacji na dany dzień (brak powtórzeń przez ~300 dni) */
export function getDailyAffirmation(dateStr: string): Affirmation {
  const d = new Date(dateStr);
  const start = new Date(d.getFullYear(), 0, 0);
  const dayOfYear = Math.floor(((d as any) - (start as any)) / 86_400_000);
  return PORTAL_AFFIRMATIONS[dayOfYear % PORTAL_AFFIRMATIONS.length];
}

export const CATEGORY_LABELS: Record<AffirmationCategory, string> = {
  love: 'Miłość',
  peace: 'Spokój',
  abundance: 'Obfitość',
  protection: 'Ochrona',
  healing: 'Uzdrowienie',
  awakening: 'Przebudzenie',
  confidence: 'Pewność siebie',
  gratitude: 'Wdzięczność',
};

export const CATEGORY_COLORS: Record<AffirmationCategory, string> = {
  love: '#F472B6',
  peace: '#60A5FA',
  abundance: '#FBBF24',
  protection: '#A78BFA',
  healing: '#34D399',
  awakening: '#FB923C',
  confidence: '#F87171',
  gratitude: '#CEAE72',
};
