#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Direct injection of batch 1 translations into all 11 language files."""
import json
from pathlib import Path

I18N = Path("D:/Soulverse/src/core/i18n")

def load(lang): return json.loads((I18N/f"{lang}.json").read_text(encoding="utf-8"))
def save(d,lang): (I18N/f"{lang}.json").write_text(json.dumps(d,ensure_ascii=False,indent=2),encoding="utf-8")

TRANSLATIONS = {
"achievements": {
  "trofeow":{"pl":"TROFEÓW","en":"TROPHIES","es":"TROFEOS","pt":"TROFÉUS","de":"TROPHÄEN","fr":"TROPHÉES","it":"TROFEI","ru":"ТРОФЕИ","ar":"الكؤوس","ja":"トロフィー","zh":"奖杯"},
  "pkt":{"pl":"pkt","en":"pts","es":"pts","pt":"pts","de":"Pkt","fr":"pts","it":"pti","ru":"оч","ar":"نقاط","ja":"ポイント","zh":"分"},
  "swiecace_gwiazdy_zdobyte_trofea":{"pl":"Świecące gwiazdy — zdobyte trofea","en":"Shining stars — earned trophies","es":"Estrellas brillantes — trofeos ganados","pt":"Estrelas brilhantes — troféus conquistados","de":"Leuchtende Sterne — verdiente Trophäen","fr":"Étoiles brillantes — trophées gagnés","it":"Stelle brillanti — trofei guadagnati","ru":"Сияющие звёзды — заработанные трофеи","ar":"النجوم المضيئة — الكؤوس المكتسبة","ja":"輝く星々 — 獲得したトロフィー","zh":"闪耀星星 — 已获奖杯"},
  "kolejne_trofea_do_zdobycia":{"pl":"Kolejne trofea do zdobycia","en":"More trophies to earn","es":"Más trofeos por ganar","pt":"Mais troféus a conquistar","de":"Weitere Trophäen zu verdienen","fr":"Plus de trophées à gagner","it":"Altri trofei da guadagnare","ru":"Ещё трофеи для получения","ar":"المزيد من الكؤوس للفوز بها","ja":"獲得できるトロフィーがまだあります","zh":"还有更多奖杯可以获得"},
  "zdobyte":{"pl":"Zdobyte","en":"Earned","es":"Ganados","pt":"Conquistados","de":"Verdient","fr":"Gagnés","it":"Guadagnati","ru":"Заработано","ar":"مكتسبة","ja":"獲得済み","zh":"已获得"},
  "ten_tydzien":{"pl":"Ten tydzień","en":"This week","es":"Esta semana","pt":"Esta semana","de":"Diese Woche","fr":"Cette semaine","it":"Questa settimana","ru":"На этой неделе","ar":"هذا الأسبوع","ja":"今週","zh":"本周"},
  "seria_dni":{"pl":"Seria dni","en":"Day streak","es":"Racha de días","pt":"Sequência de dias","de":"Tagesserie","fr":"Série de jours","it":"Serie di giorni","ru":"Серия дней","ar":"سلسلة الأيام","ja":"日連続","zh":"连续天数"},
  "najrzadsze":{"pl":"Najrzadsze","en":"Rarest","es":"Más raros","pt":"Mais raros","de":"Seltenste","fr":"Les plus rares","it":"Più rari","ru":"Самые редкие","ar":"الأندر","ja":"最もレア","zh":"最稀有"},
},
"aetherLive": {
  "uzupelnij":{"pl":"Uzupełnij","en":"Complete","es":"Completar","pt":"Completar","de":"Ausfüllen","fr":"Compléter","it":"Completa","ru":"Заполнить","ar":"أكمل","ja":"完成させる","zh":"完成"},
  "podaj_tytul_transmisji":{"pl":"Podaj tytuł transmisji.","en":"Enter stream title.","es":"Ingresa el título del stream.","pt":"Insira o título da transmissão.","de":"Titel des Streams eingeben.","fr":"Entrez le titre du stream.","it":"Inserisci il titolo della trasmissione.","ru":"Введите название трансляции.","ar":"أدخل عنوان البث.","ja":"ストリームタイトルを入力してください。","zh":"输入直播标题。"},
  "jestes_na_zywo":{"pl":"✦ Jesteś NA ŻYWO","en":"✦ You're LIVE","es":"✦ Estás EN VIVO","pt":"✦ Você está AO VIVO","de":"✦ Du bist LIVE","fr":"✦ Tu es EN DIRECT","it":"✦ Sei IN DIRETTA","ru":"✦ Ты в прямом эфире","ar":"✦ أنت مباشر الآن","ja":"✦ ライブ配信中","zh":"✦ 你正在直播"},
  "twoja_transmisja_jest_aktywna_witaj":{"pl":"Twoja transmisja jest aktywna. Witaj społeczność!","en":"Your stream is active. Welcome the community!","es":"Tu transmisión está activa. ¡Bienvenida a la comunidad!","pt":"Sua transmissão está ativa. Bem-vindo à comunidade!","de":"Dein Stream ist aktiv. Willkommen in der Gemeinschaft!","fr":"Ton stream est actif. Bienvenue dans la communauté !","it":"La tua trasmissione è attiva. Benvenuti alla comunità!","ru":"Ваша трансляция активна. Добро пожаловать в сообщество!","ar":"بثك نشط. مرحباً بالمجتمع!","ja":"ストリームが開始されました。コミュニティへようこそ！","zh":"您的直播已开始。欢迎社区！"},
  "blad":{"pl":"Błąd","en":"Error","es":"Error","pt":"Erro","de":"Fehler","fr":"Erreur","it":"Errore","ru":"Ошибка","ar":"خطأ","ja":"エラー","zh":"错误"},
  "nie_udalo_sie_uruchomic_transmisji":{"pl":"Nie udało się uruchomić transmisji. Spróbuj ponownie.","en":"Failed to start stream. Try again.","es":"No se pudo iniciar el stream. Inténtalo de nuevo.","pt":"Falha ao iniciar a transmissão. Tente novamente.","de":"Stream konnte nicht gestartet werden. Erneut versuchen.","fr":"Échec du démarrage du stream. Réessaie.","it":"Impossibile avviare la trasmissione. Riprova.","ru":"Не удалось начать трансляцию. Попробуйте снова.","ar":"فشل في بدء البث. حاول مرة أخرى.","ja":"ストリームを開始できませんでした。再試行してください。","zh":"无法启动直播。请重试。"},
},
"affirmations": {
  "wsparcie":{"pl":"Wsparcie","en":"Support","es":"Apoyo","pt":"Apoio","de":"Unterstützung","fr":"Soutien","it":"Supporto","ru":"Поддержка","ar":"الدعم","ja":"サポート","zh":"支持"},
  "afirmacje":{"pl":"Afirmacje","en":"Affirmations","es":"Afirmaciones","pt":"Afirmações","de":"Affirmationen","fr":"Affirmations","it":"Affermazioni","ru":"Аффирмации","ar":"التأكيدات","ja":"アファメーション","zh":"肯定语"},
  "handoff_z_rytualu":{"pl":"HANDOFF Z RYTUAŁU","en":"RITUAL HANDOFF","es":"TRANSICIÓN DEL RITUAL","pt":"TRANSIÇÃO DO RITUAL","de":"RITUAL-ÜBERGABE","fr":"TRANSFERT DU RITUEL","it":"PASSAGGIO DAL RITUALE","ru":"ПЕРЕДАЧА ОТ РИТУАЛА","ar":"انتقال الطقس","ja":"リチュアル引き継ぎ","zh":"仪式交接"},
  "udostepnij_afirmacje":{"pl":"Udostępnij afirmację","en":"Share affirmation","es":"Compartir afirmación","pt":"Compartilhar afirmação","de":"Affirmation teilen","fr":"Partager l'affirmation","it":"Condividi affermazione","ru":"Поделиться аффирмацией","ar":"شارك التأكيد","ja":"アファメーションをシェア","zh":"分享肯定语"},
  "mantra_tygodnia":{"pl":"MANTRA TYGODNIA","en":"MANTRA OF THE WEEK","es":"MANTRA DE LA SEMANA","pt":"MANTRA DA SEMANA","de":"MANTRA DER WOCHE","fr":"MANTRA DE LA SEMAINE","it":"MANTRA DELLA SETTIMANA","ru":"МАНТРА НЕДЕЛИ","ar":"مانترا الأسبوع","ja":"今週のマントラ","zh":"本周曼陀罗"},
  "nowa_mantra_kazdego_tygodnia":{"pl":"Nowa mantra każdego tygodnia","en":"New mantra every week","es":"Nueva mantra cada semana","pt":"Nova mantra toda semana","de":"Jede Woche eine neue Mantra","fr":"Nouveau mantra chaque semaine","it":"Nuovo mantra ogni settimana","ru":"Новая мантра каждую неделю","ar":"مانترا جديدة كل أسبوع","ja":"毎週新しいマントラ","zh":"每周新曼陀罗"},
  "afirmacja_godziny":{"pl":"AFIRMACJA GODZINY","en":"AFFIRMATION OF THE HOUR","es":"AFIRMACIÓN DE LA HORA","pt":"AFIRMAÇÃO DA HORA","de":"AFFIRMATION DER STUNDE","fr":"AFFIRMATION DE L'HEURE","it":"AFFERMAZIONE DELL'ORA","ru":"АФФИРМАЦИЯ ЧАСА","ar":"تأكيد الساعة","ja":"時間のアファメーション","zh":"本小时肯定语"},
  "udostepnij_te_chwile":{"pl":"Udostępnij tę chwilę","en":"Share this moment","es":"Comparte este momento","pt":"Compartilha este momento","de":"Teile diesen Moment","fr":"Partage ce moment","it":"Condividi questo momento","ru":"Поделись этим моментом","ar":"شارك هذه اللحظة","ja":"この瞬間をシェア","zh":"分享这一刻"},
  "jak_dziala_wsparcie":{"pl":"Jak działa wsparcie","en":"How support works","es":"Cómo funciona el apoyo","pt":"Como o apoio funciona","de":"Wie Unterstützung funktioniert","fr":"Comment fonctionne le soutien","it":"Come funziona il supporto","ru":"Как работает поддержка","ar":"كيف يعمل الدعم","ja":"サポートの仕組み","zh":"支持如何运作"},
  "cwiczenie_lustrzane":{"pl":"ĆWICZENIE LUSTRZANE","en":"MIRROR EXERCISE","es":"EJERCICIO DEL ESPEJO","pt":"EXERCÍCIO DO ESPELHO","de":"SPIEGELÜBUNG","fr":"EXERCICE DU MIROIR","it":"ESERCIZIO DELLO SPECCHIO","ru":"ЗЕРКАЛЬНОЕ УПРАЖНЕНИЕ","ar":"تمرين المرآة","ja":"鏡エクササイズ","zh":"镜子练习"},
  "powiedz_afirmacje_patrzac_sobie_w":{"pl":"Powiedz afirmację patrząc sobie w oczy","en":"Say the affirmation looking into your own eyes","es":"Di la afirmación mirándote a los ojos","pt":"Diga a afirmação olhando nos seus próprios olhos","de":"Sag die Affirmation und schau dir dabei in die Augen","fr":"Dis l'affirmation en te regardant dans les yeux","it":"Dì l'affermazione guardandoti negli occhi","ru":"Произнеси аффирмацию, глядя себе в глаза","ar":"قل التأكيد وأنت تنظر في عينيك","ja":"自分の目を見ながらアファメーションを言う","zh":"看着自己的眼睛说出肯定语"},
  "gotowe":{"pl":"Gotowe","en":"Done","es":"Listo","pt":"Pronto","de":"Fertig","fr":"Terminé","it":"Fatto","ru":"Готово","ar":"تم","ja":"完了","zh":"完成"},
  "swieta_liczba_w_tradycji_wedyjskiej":{"pl":"Święta liczba w tradycji wedyjskiej","en":"Sacred number in Vedic tradition","es":"Número sagrado en la tradición védica","pt":"Número sagrado na tradição védica","de":"Heilige Zahl in der vedischen Tradition","fr":"Nombre sacré dans la tradition védique","it":"Numero sacro nella tradizione vedica","ru":"Священное число в ведической традиции","ar":"الرقم المقدس في التقليد الفيدي","ja":"ヴェーダの伝統における聖なる数字","zh":"吠陀传统中的神圣数字"},
  "rozpocznij_praktyke":{"pl":"Rozpocznij praktykę","en":"Begin practice","es":"Comenzar práctica","pt":"Começar prática","de":"Praxis beginnen","fr":"Commencer la pratique","it":"Inizia la pratica","ru":"Начать практику","ar":"ابدأ الممارسة","ja":"プラクティスを開始","zh":"开始练习"},
  "jedno_powtorzeni":{"pl":"jedno powtórzenie","en":"one repetition","es":"una repetición","pt":"uma repetição","de":"eine Wiederholung","fr":"une répétition","it":"una ripetizione","ru":"одно повторение","ar":"تكرار واحد","ja":"1回の繰り返し","zh":"一次重复"},
  "reset":{"pl":"Reset","en":"Reset","es":"Restablecer","pt":"Reiniciar","de":"Zurücksetzen","fr":"Réinitialiser","it":"Reimposta","ru":"Сбросить","ar":"إعادة تعيين","ja":"リセット","zh":"重置"},
  "tryb_audio_rytm_oddechu":{"pl":"TRYB AUDIO — RYTM ODDECHU","en":"AUDIO MODE — BREATHING RHYTHM","es":"MODO AUDIO — RITMO DE RESPIRACIÓN","pt":"MODO ÁUDIO — RITMO DE RESPIRAÇÃO","de":"AUDIOMODUS — ATEMRHYTHMUS","fr":"MODE AUDIO — RYTHME RESPIRATOIRE","it":"MODALITÀ AUDIO — RITMO RESPIRATORIO","ru":"АУДИОРЕЖИМ — РИТМ ДЫХАНИЯ","ar":"وضع الصوت — إيقاع التنفس","ja":"オーディオモード — 呼吸リズム","zh":"音频模式 — 呼吸节奏"},
  "sekwencja_na_dzis":{"pl":"Sekwencja na dziś","en":"Today's sequence","es":"Secuencia de hoy","pt":"Sequência de hoje","de":"Heutige Sequenz","fr":"Séquence du jour","it":"Sequenza di oggi","ru":"Последовательность на сегодня","ar":"تسلسل اليوم","ja":"今日のシークエンス","zh":"今日序列"},
  "moje_ulubione":{"pl":"MOJE ULUBIONE","en":"MY FAVORITES","es":"MIS FAVORITOS","pt":"MEUS FAVORITOS","de":"MEINE FAVORITEN","fr":"MES FAVORIS","it":"I MIEI PREFERITI","ru":"МОИ ИЗБРАННЫЕ","ar":"مفضلاتي","ja":"お気に入り","zh":"我的收藏"},
  "historia_afirmacji":{"pl":"HISTORIA AFIRMACJI","en":"AFFIRMATION HISTORY","es":"HISTORIAL DE AFIRMACIONES","pt":"HISTÓRICO DE AFIRMAÇÕES","de":"AFFIRMATIONSHISTORIE","fr":"HISTORIQUE DES AFFIRMATIONS","it":"CRONOLOGIA AFFERMAZIONI","ru":"ИСТОРИЯ АФФИРМАЦИЙ","ar":"تاريخ التأكيدات","ja":"アファメーション履歴","zh":"肯定语历史"},
  "kazdy_dzien_z_afirmacja_zapisuje":{"pl":"Każdy dzień z afirmacją zapisuje się tutaj. Kolor odpowiada kategorii praktyki.","en":"Every day with an affirmation is recorded here. The color corresponds to the practice category.","es":"Cada día con una afirmación se registra aquí. El color corresponde a la categoría de práctica.","pt":"Cada dia com uma afirmação é registrado aqui. A cor corresponde à categoria de prática.","de":"Jeder Tag mit einer Affirmation wird hier aufgezeichnet. Die Farbe entspricht der Übungskategorie.","fr":"Chaque jour avec une affirmation est enregistré ici. La couleur correspond à la catégorie de pratique.","it":"Ogni giorno con un'affermazione viene registrato qui. Il colore corrisponde alla categoria di pratica.","ru":"Каждый день с аффирмацией записывается здесь. Цвет соответствует категории практики.","ar":"كل يوم مع تأكيد يُسجَّل هنا. اللون يتوافق مع فئة الممارسة.","ja":"アファメーションのある毎日がここに記録されます。色は練習カテゴリに対応します。","zh":"每个有肯定语的日子都记录在这里。颜色对应练习类别。"},
  "wyzwanie_21_dni":{"pl":"WYZWANIE 21 DNI","en":"21-DAY CHALLENGE","es":"RETO 21 DÍAS","pt":"DESAFIO 21 DIAS","de":"21-TAGE-CHALLENGE","fr":"DÉFI 21 JOURS","it":"SFIDA 21 GIORNI","ru":"ВЫЗОВ 21 ДЕНЬ","ar":"تحدي 21 يوماً","ja":"21日チャレンジ","zh":"21天挑战"},
  "codziennie_przez_3_tygodnie":{"pl":"Codziennie przez 3 tygodnie","en":"Every day for 3 weeks","es":"Todos los días durante 3 semanas","pt":"Todos os dias por 3 semanas","de":"Jeden Tag für 3 Wochen","fr":"Chaque jour pendant 3 semaines","it":"Ogni giorno per 3 settimane","ru":"Каждый день в течение 3 недель","ar":"كل يوم لمدة 3 أسابيع","ja":"3週間毎日","zh":"每天坚持3周"},
  "dotknij_dnia_aby_oznaczyc_go":{"pl":"Dotknij dnia, aby oznaczyć go jako ukończony. Badania pokazują, że 21 dni wystarczy, aby nowa praktyka stała się nawykowym wzorcem.","en":"Tap a day to mark it as complete. Research shows 21 days is enough for a new practice to become a habitual pattern.","es":"Toca un día para marcarlo como completado. La investigación muestra que 21 días son suficientes para que una nueva práctica se convierta en hábito.","pt":"Toque em um dia para marcá-lo como concluído. Pesquisas mostram que 21 dias são suficientes para uma nova prática se tornar um padrão habitual.","de":"Tippe auf einen Tag, um ihn als abgeschlossen zu markieren. Forschungen zeigen, dass 21 Tage ausreichen, damit eine neue Praxis zu einem Gewohnheitsmuster wird.","fr":"Appuie sur un jour pour le marquer comme terminé. Les recherches montrent que 21 jours suffisent pour qu'une nouvelle pratique devienne un schéma habituel.","it":"Tocca un giorno per contrassegnarlo come completato. La ricerca mostra che 21 giorni sono sufficienti perché una nuova pratica diventi un modello abituale.","ru":"Нажмите на день, чтобы отметить его как выполненный. Исследования показывают, что 21 дня достаточно, чтобы новая практика стала привычным паттерном.","ar":"اضغط على يوم لتحديده كمكتمل. تُظهر الأبحاث أن 21 يوماً كافية لتصبح ممارسة جديدة نمطاً اعتيادياً.","ja":"日をタップして完了としてマーク。研究によると、新しい習慣が定着するには21日間で十分です。","zh":"点击某天将其标记为完成。研究表明，21天足以让新练习成为习惯模式。"},
  "wyzwanie_ukonczone":{"pl":"Wyzwanie ukończone! ✨","en":"Challenge complete! ✨","es":"¡Reto completado! ✨","pt":"Desafio concluído! ✨","de":"Challenge abgeschlossen! ✨","fr":"Défi terminé ! ✨","it":"Sfida completata! ✨","ru":"Вызов завершён! ✨","ar":"اكتمل التحدي! ✨","ja":"チャレンジ完了！ ✨","zh":"挑战完成！ ✨"},
  "powtorz_trzy_razy_powoli_i":{"pl":"Powtórz trzy razy powoli i sprawdź, gdzie w ciele pojawia się ulga.","en":"Repeat three times slowly and notice where relief appears in the body.","es":"Repite tres veces lentamente y observa dónde aparece el alivio en el cuerpo.","pt":"Repita três vezes devagar e observe onde o alívio aparece no corpo.","de":"Wiederhole dreimal langsam und beobachte, wo Erleichterung im Körper entsteht.","fr":"Répète trois fois lentement et remarque où le soulagement apparaît dans le corps.","it":"Ripeti tre volte lentamente e nota dove appare il sollievo nel corpo.","ru":"Повторите три раза медленно и замечайте, где в теле появляется облегчение.","ar":"كرر ثلاث مرات ببطء ولاحظ أين يظهر الارتياح في الجسم.","ja":"ゆっくりと3回繰り返し、体のどこに安らぎが現れるかに気づいてください。","zh":"慢慢重复三次，感受身体哪里出现了释然。"},
  "czytaj_jak_wers_nie_jak":{"pl":"Czytaj jak wers, nie jak notatkę","en":"Read it like a verse, not a note","es":"Léelo como un verso, no como una nota","pt":"Leia como um verso, não como uma nota","de":"Lies es wie einen Vers, nicht wie eine Notiz","fr":"Lis-le comme un vers, pas comme une note","it":"Leggilo come un verso, non come una nota","ru":"Читай как стих, а не как заметку","ar":"اقرأها كآية وليس كملاحظة","ja":"メモではなく詩として読む","zh":"像诗句一样读，而不是像笔记"},
  "udostepnij":{"pl":"Udostępnij","en":"Share","es":"Compartir","pt":"Compartilhar","de":"Teilen","fr":"Partager","it":"Condividi","ru":"Поделиться","ar":"مشاركة","ja":"シェア","zh":"分享"},
  "ekosystem_wsparcia":{"pl":"Ekosystem wsparcia","en":"Support ecosystem","es":"Ecosistema de apoyo","pt":"Ecossistema de apoio","de":"Unterstützungsökosystem","fr":"Écosystème de soutien","it":"Ecosistema di supporto","ru":"Экосистема поддержки","ar":"نظام الدعم","ja":"サポートエコシステム","zh":"支持生态系统"},
  "nauka_o_afirmacjac":{"pl":"Nauka o afirmacjach","en":"Science of affirmations","es":"Ciencia de las afirmaciones","pt":"Ciência das afirmações","de":"Wissenschaft der Affirmationen","fr":"Science des affirmations","it":"Scienza delle affermazioni","ru":"Наука об аффирмациях","ar":"علم التأكيدات","ja":"アファメーションの科学","zh":"肯定语科学"},
  "domknij_wsparcie_zapisem":{"pl":"Domknij wsparcie zapisem","en":"Complete support with a journal entry","es":"Completa el apoyo con una entrada en el diario","pt":"Complete o apoio com uma entrada no diário","de":"Schließe die Unterstützung mit einem Tagebucheintrag ab","fr":"Complète le soutien avec une entrée dans le journal","it":"Completa il supporto con una voce nel diario","ru":"Завершите поддержку записью в дневнике","ar":"أكمل الدعم بإدخال في المجلة","ja":"日記への記入でサポートを完了する","zh":"用日记条目完成支持"},
  "jesli_chcesz_zeby_to_zdanie":{"pl":"Jeśli chcesz, żeby to zdanie naprawdę zostało z Tobą, zapisz jedno zdanie o tym, co poruszyło się po jego powtórzeniu.","en":"If you want this sentence to truly stay with you, write one sentence about what shifted after repeating it.","es":"Si quieres que esta frase realmente se quede contigo, escribe una oración sobre lo que cambió después de repetirla.","pt":"Se você quiser que esta frase realmente fique com você, escreva uma frase sobre o que mudou após repeti-la.","de":"Wenn du möchtest, dass dieser Satz wirklich bei dir bleibt, schreibe einen Satz darüber, was sich nach dem Wiederholen verändert hat.","fr":"Si tu veux que cette phrase reste vraiment avec toi, écris une phrase sur ce qui a changé après l'avoir répétée.","it":"Se vuoi che questa frase rimanga davvero con te, scrivi una frase su cosa è cambiato dopo averla ripetuta.","ru":"Если вы хотите, чтобы это предложение действительно осталось с вами, напишите одно предложение о том, что изменилось после его повторения.","ar":"إذا أردت أن تبقى هذه الجملة معك حقاً، اكتب جملة واحدة عما تغيّر بعد تكرارها.","ja":"この言葉が本当に心に残るように、繰り返した後に何が変わったかについて一文書いてください。","zh":"如果你希望这句话真正留在心中，请写一句话描述重复后发生了什么改变。"},
  "przejdz_do_dziennika":{"pl":"Przejdź do dziennika","en":"Go to journal","es":"Ir al diario","pt":"Ir para o diário","de":"Zum Tagebuch gehen","fr":"Aller au journal","it":"Vai al diario","ru":"Перейти к дневнику","ar":"الذهاب إلى المجلة","ja":"ジャーナルへ","zh":"前往日记"},
  "dla_kogo_te_afirmacje":{"pl":"Dla kogo te afirmacje?","en":"Who are these affirmations for?","es":"¿Para quién son estas afirmaciones?","pt":"Para quem são essas afirmações?","de":"Für wen sind diese Affirmationen?","fr":"Pour qui sont ces affirmations ?","it":"Per chi sono queste affermazioni?","ru":"Для кого эти аффирмации?","ar":"لمن هذه التأكيدات؟","ja":"このアファメーションは誰のため？","zh":"这些肯定语是为谁准备的？"},
  "wpisz_imie_osoby_ktorej_poswiecasz":{"pl":"Wpisz imię osoby, której poświęcasz tę sesję.","en":"Enter the name of the person you dedicate this session to.","es":"Ingresa el nombre de la persona a quien dedicas esta sesión.","pt":"Insira o nome da pessoa a quem você dedica esta sessão.","de":"Gib den Namen der Person ein, der du diese Sitzung widmest.","fr":"Entre le nom de la personne à qui tu dédies cette session.","it":"Inserisci il nome della persona a cui dedichi questa sessione.","ru":"Введите имя человека, которому вы посвящаете эту сессию.","ar":"أدخل اسم الشخص الذي تهدي له هذه الجلسة.","ja":"このセッションを捧げる人の名前を入力してください。","zh":"输入您将此会话奉献给的人的姓名。"},
  "wylacz_tryb_dla_kogos":{"pl":"Wyłącz tryb \"Dla kogoś\"","en":"Turn off \"For someone\" mode","es":"Desactivar modo \"Para alguien\"","pt":"Desativar modo \"Para alguém\"","de":"Modus \"Für jemanden\" deaktivieren","fr":"Désactiver le mode \"Pour quelqu'un\"","it":"Disattiva modalità \"Per qualcuno\"","ru":"Отключить режим «Для кого-то»","ar":"إيقاف وضع \"لشخص ما\"","ja":"「誰かのために」モードをオフにする","zh":"关闭"为某人"模式"},
  "potwierdz":{"pl":"Potwierdź","en":"Confirm","es":"Confirmar","pt":"Confirmar","de":"Bestätigen","fr":"Confirmer","it":"Conferma","ru":"Подтвердить","ar":"تأكيد","ja":"確認","zh":"确认"},
  "wlasna_afirmacja":{"pl":"Własna afirmacja","en":"My own affirmation","es":"Mi propia afirmación","pt":"Minha própria afirmação","de":"Eigene Affirmation","fr":"Ma propre affirmation","it":"La mia affermazione","ru":"Своя аффирмация","ar":"تأكيدي الخاص","ja":"自分のアファメーション","zh":"我的肯定语"},
  "nadaj_swojej_intencji_wlasny_jezyk":{"pl":"Nadaj swojej intencji własny język.","en":"Give your intention its own language.","es":"Dale a tu intención su propio lenguaje.","pt":"Dê à sua intenção sua própria linguagem.","de":"Gib deiner Intention ihre eigene Sprache.","fr":"Donne à ton intention son propre langage.","it":"Dai alla tua intenzione il suo linguaggio.","ru":"Дайте своему намерению собственный язык.","ar":"امنح نيتك لغتها الخاصة.","ja":"自分の意図に独自の言葉を与えてください。","zh":"赋予你的意图其独特的语言。"},
  "najmocniej_dziala_zdanie_krotkie_od":{"pl":"Najmocniej działa zdanie krótkie, oddechowe i prawdziwe. Zapisz je tak, aby brzmiało jak coś, do czego naprawdę chcesz wracać rano albo wieczorem.","en":"The most powerful sentence is short, breathable, and true. Write it so it sounds like something you truly want to return to in the morning or evening.","es":"La frase más poderosa es corta, respirable y verdadera. Escríbela para que suene como algo a lo que realmente quieras volver por la mañana o por la noche.","pt":"A frase mais poderosa é curta, respirável e verdadeira. Escreva-a de forma que soe como algo ao qual você realmente quer voltar de manhã ou à noite.","de":"Der wirkungsvollste Satz ist kurz, atembar und wahr. Schreibe ihn so, dass er wie etwas klingt, zu dem du morgens oder abends wirklich zurückkehren möchtest.","fr":"La phrase la plus puissante est courte, respirable et vraie. Écris-la de sorte qu'elle sonne comme quelque chose vers lequel tu veux vraiment revenir le matin ou le soir.","it":"La frase più potente è breve, respirabile e vera. Scrivila in modo che suoni come qualcosa a cui vuoi davvero tornare mattina o sera.","ru":"Самое действенное предложение — короткое, дышащее и правдивое. Запишите его так, чтобы оно звучало как то, к чему вы действительно хотите возвращаться утром или вечером.","ar":"أقوى جملة هي قصيرة وقابلة للتنفس وصادقة. اكتبها بحيث تبدو كشيء تريد حقاً العودة إليه صباحاً أو مساءً.","ja":"最も力強い文章は短く、呼吸しやすく、真実です。朝や夜に本当に戻りたいと思えるように書いてください。","zh":"最有力量的句子是简短、可呼吸且真实的。写下来，让它听起来像是你真正想在早晨或晚上回归的东西。"},
  "anuluj":{"pl":"Anuluj","en":"Cancel","es":"Cancelar","pt":"Cancelar","de":"Abbrechen","fr":"Annuler","it":"Annulla","ru":"Отмена","ar":"إلغاء","ja":"キャンセル","zh":"取消"},
  "zapisz_afirmacje":{"pl":"Zapisz afirmację","en":"Save affirmation","es":"Guardar afirmación","pt":"Salvar afirmação","de":"Affirmation speichern","fr":"Enregistrer l'affirmation","it":"Salva affermazione","ru":"Сохранить аффирмацию","ar":"حفظ التأكيد","ja":"アファメーションを保存","zh":"保存肯定语"},
  "imie_osoby":{"pl":"Imię osoby...","en":"Person's name...","es":"Nombre de la persona...","pt":"Nome da pessoa...","de":"Name der Person...","fr":"Nom de la personne...","it":"Nome della persona...","ru":"Имя человека...","ar":"اسم الشخص...","ja":"人の名前...","zh":"人名..."},
  "np_z_kazdym_oddechem_odzyskuje":{"pl":"Np. Z każdym oddechem odzyskuję spokój i wracam do swojego centrum.","en":"E.g. With every breath I reclaim peace and return to my center.","es":"Ej. Con cada respiración recupero la paz y regreso a mi centro.","pt":"Ex. A cada respiração recupero a paz e retorno ao meu centro.","de":"Z.B. Mit jedem Atemzug gewinne ich Frieden zurück und kehre zu meiner Mitte zurück.","fr":"Ex. À chaque souffle, je retrouve la paix et reviens à mon centre.","it":"Es. Ad ogni respiro riprendo la pace e torno al mio centro.","ru":"Например: С каждым вдохом я восстанавливаю покой и возвращаюсь к своему центру.","ar":"مثال: مع كل نفس أستعيد السلام وأعود إلى مركزي.","ja":"例：息を吸うたびに平和を取り戻し、自分の中心に戻ります。","zh":"例如：每次呼吸我都找回平静，回归自我中心。"},
  "usun_afirmacje":{"pl":"Usuń afirmację","en":"Delete affirmation","es":"Eliminar afirmación","pt":"Excluir afirmação","de":"Affirmation löschen","fr":"Supprimer l'affirmation","it":"Elimina affermazione","ru":"Удалить аффирмацию","ar":"حذف التأكيد","ja":"アファメーションを削除","zh":"删除肯定语"},
  "czy_na_pewno_chcesz_usunac":{"pl":"Czy na pewno chcesz usunąć tę afirmację?","en":"Are you sure you want to delete this affirmation?","es":"¿Estás seguro de que deseas eliminar esta afirmación?","pt":"Tem certeza de que deseja excluir esta afirmação?","de":"Bist du sicher, dass du diese Affirmation löschen möchtest?","fr":"Es-tu sûr de vouloir supprimer cette affirmation ?","it":"Sei sicuro di voler eliminare questa affermazione?","ru":"Вы уверены, что хотите удалить эту аффирмацию?","ar":"هل أنت متأكد أنك تريد حذف هذا التأكيد؟","ja":"このアファメーションを削除してもよろしいですか？","zh":"您确定要删除此肯定语吗？"},
},
"aiDailyAff": {
  "tygodniowy_kalendarz_afirmacji":{"pl":"TYGODNIOWY KALENDARZ AFIRMACJI","en":"WEEKLY AFFIRMATION CALENDAR","es":"CALENDARIO SEMANAL DE AFIRMACIONES","pt":"CALENDÁRIO SEMANAL DE AFIRMAÇÕES","de":"WÖCHENTLICHER AFFIRMATIONSKALENDER","fr":"CALENDRIER HEBDOMADAIRE D'AFFIRMATIONS","it":"CALENDARIO SETTIMANALE AFFERMAZIONI","ru":"ЕЖЕНЕДЕЛЬНЫЙ КАЛЕНДАРЬ АФФИРМАЦИЙ","ar":"تقويم التأكيدات الأسبوعي","ja":"週間アファメーションカレンダー","zh":"每周肯定语日历"},
  "dotknij_gwiazdek_zeby_ocenic_rezona":{"pl":"Dotknij gwiazdek, żeby ocenić rezonans afirmacji danego dnia.","en":"Tap the stars to rate the resonance of the affirmation for that day.","es":"Toca las estrellas para calificar la resonancia de la afirmación del día.","pt":"Toque nas estrelas para avaliar a ressonância da afirmação do dia.","de":"Tippe auf die Sterne, um die Resonanz der Affirmation des Tages zu bewerten.","fr":"Appuie sur les étoiles pour noter la résonance de l'affirmation du jour.","it":"Tocca le stelle per valutare la risonanza dell'affermazione del giorno.","ru":"Нажмите на звёзды, чтобы оценить резонанс аффирмации этого дня.","ar":"اضغط على النجوم لتقييم صدى تأكيد ذلك اليوم.","ja":"星をタップして、その日のアファメーションの共鳴を評価する。","zh":"点击星星为当天肯定语的共鸣打分。"},
  "wzorzec_oddechowy_4_2_6":{"pl":"Wzorzec oddechowy 4-2-6 aktywuje spokój układu nerwowego.","en":"The 4-2-6 breathing pattern activates nervous system calm.","es":"El patrón respiratorio 4-2-6 activa la calma del sistema nervioso.","pt":"O padrão respiratório 4-2-6 ativa a calma do sistema nervoso.","de":"Das 4-2-6-Atemmuster aktiviert die Ruhe des Nervensystems.","fr":"Le schéma respiratoire 4-2-6 active le calme du système nerveux.","it":"Lo schema respiratorio 4-2-6 attiva la calma del sistema nervoso.","ru":"Дыхательный паттерн 4-2-6 активирует спокойствие нервной системы.","ar":"نمط التنفس 4-2-6 يُنشّط هدوء الجهاز العصبي.","ja":"4-2-6呼吸パターンが神経系の落ち着きを活性化します。","zh":"4-2-6呼吸模式激活神经系统的平静。"},
  "sterowanie_generowani":{"pl":"STEROWANIE GENEROWANIEM","en":"GENERATION CONTROLS","es":"CONTROLES DE GENERACIÓN","pt":"CONTROLES DE GERAÇÃO","de":"GENERIERUNGSSTEUERUNG","fr":"CONTRÔLES DE GÉNÉRATION","it":"CONTROLLI GENERAZIONE","ru":"УПРАВЛЕНИЕ ГЕНЕРАЦИЕЙ","ar":"ضوابط التوليد","ja":"生成コントロール","zh":"生成控制"},
  "ustawienia_wplywaja_na_nastepne_gen":{"pl":"Ustawienia wpływają na następne generowanie. Odśwież, aby zastosować.","en":"Settings affect the next generation. Refresh to apply.","es":"La configuración afecta la próxima generación. Actualiza para aplicar.","pt":"As configurações afetam a próxima geração. Atualize para aplicar.","de":"Einstellungen beeinflussen die nächste Generierung. Aktualisieren, um anzuwenden.","fr":"Les paramètres affectent la prochaine génération. Actualise pour appliquer.","it":"Le impostazioni influenzano la prossima generazione. Aggiorna per applicare.","ru":"Настройки влияют на следующую генерацию. Обновите, чтобы применить.","ar":"الإعدادات تؤثر على الجيل القادم. حدّث للتطبيق.","ja":"設定は次の生成に影響します。適用するには更新してください。","zh":"设置影响下一次生成。刷新以应用。"},
  "brak_zapisanych_afirmacji":{"pl":"Brak zapisanych afirmacji","en":"No saved affirmations","es":"No hay afirmaciones guardadas","pt":"Nenhuma afirmação salva","de":"Keine gespeicherten Affirmationen","fr":"Aucune affirmation enregistrée","it":"Nessuna affermazione salvata","ru":"Нет сохранённых аффирмаций","ar":"لا توجد تأكيدات محفوظة","ja":"保存されたアファメーションなし","zh":"没有保存的肯定语"},
  "dotknij_przy_afirmacji_aby_zapisac":{"pl":"Dotknij ♡ przy afirmacji, aby zapisać ją w dzienniku.","en":"Tap ♡ next to an affirmation to save it to your journal.","es":"Toca ♡ junto a una afirmación para guardarla en tu diario.","pt":"Toque em ♡ ao lado de uma afirmação para salvá-la no diário.","de":"Tippe ♡ neben einer Affirmation, um sie in deinem Tagebuch zu speichern.","fr":"Appuie sur ♡ à côté d'une affirmation pour la sauvegarder dans ton journal.","it":"Tocca ♡ accanto a un'affermazione per salvarla nel diario.","ru":"Нажмите ♡ рядом с аффирмацией, чтобы сохранить её в дневнике.","ar":"اضغط ♡ بجانب التأكيد لحفظه في مجلتك.","ja":"アファメーションの横の♡をタップしてジャーナルに保存する。","zh":"点击肯定语旁边的♡将其保存到日记中。"},
  "zapisz_refleksje":{"pl":"Zapisz refleksję","en":"Save reflection","es":"Guardar reflexión","pt":"Salvar reflexão","de":"Reflexion speichern","fr":"Enregistrer la réflexion","it":"Salva riflessione","ru":"Сохранить рефлексию","ar":"حفظ التأمل","ja":"振り返りを保存","zh":"保存反思"},
  "afirmacje_ai":{"pl":"Afirmacje AI","en":"AI Affirmations","es":"Afirmaciones IA","pt":"Afirmações IA","de":"KI-Affirmationen","fr":"Affirmations IA","it":"Affermazioni IA","ru":"Аффирмации ИИ","ar":"تأكيدات الذكاء الاصطناعي","ja":"AIアファメーション","zh":"AI肯定语"},
  "codzienne_slowa_mocy":{"pl":"Codzienne słowa mocy","en":"Daily words of power","es":"Palabras de poder diarias","pt":"Palavras de poder diárias","de":"Tägliche Kraftworte","fr":"Mots de pouvoir quotidiens","it":"Parole di potere quotidiane","ru":"Ежедневные слова силы","ar":"كلمات القوة اليومية","ja":"毎日のパワーワード","zh":"每日力量之词"},
  "zatrzymaj_sie_na_moment_i":{"pl":"Zatrzymaj się na moment i wybierz słowa, które dziś mają stać się Twoim wewnętrznym kierunkiem.","en":"Pause for a moment and choose the words that will become your inner compass today.","es":"Detente un momento y elige las palabras que hoy serán tu brújula interior.","pt":"Faça uma pausa por um momento e escolha as palavras que hoje se tornarão sua bússola interior.","de":"Halte einen Moment inne und wähle die Worte, die heute dein innerer Kompass sein sollen.","fr":"Arrête-toi un moment et choisis les mots qui seront ta boussole intérieure aujourd'hui.","it":"Fermati un momento e scegli le parole che oggi diventeranno la tua bussola interiore.","ru":"Остановитесь на мгновение и выберите слова, которые сегодня станут вашим внутренним компасом.","ar":"توقف لحظة واختر الكلمات التي ستصبح بوصلتك الداخلية اليوم.","ja":"少し立ち止まり、今日あなたの内なる羅針盤となる言葉を選んでください。","zh":"停顿片刻，选择今天将成为你内在指南针的话语。"},
  "nastroj_przewodni":{"pl":"Nastrój przewodni","en":"Guiding mood","es":"Estado de ánimo guía","pt":"Humor orientador","de":"Leitstimmung","fr":"Humeur directrice","it":"Umore guida","ru":"Ведущее настроение","ar":"المزاج الموجّه","ja":"導く気分","zh":"引导情绪"},
  "oracle_uklada_dla_ciebie_spokojny":{"pl":"Oracle układa dla Ciebie spokojny zestaw afirmacji...","en":"Oracle is composing a serene set of affirmations for you...","es":"Oracle está componiendo un sereno conjunto de afirmaciones para ti...","pt":"Oracle está compondo um sereno conjunto de afirmações para você...","de":"Oracle stellt für dich eine ruhige Sammlung von Affirmationen zusammen...","fr":"Oracle compose pour toi un ensemble serein d'affirmations...","it":"Oracle sta componendo per te un sereno insieme di affermazioni...","ru":"Oracle составляет для вас спокойный набор аффирмаций...","ar":"Oracle يُعدّ لك مجموعة هادئة من التأكيدات...","ja":"OracleがあなたのためにAffirmationの穏やかなセットを作成しています...","zh":"Oracle正在为您编排一套宁静的肯定语..."},
  "powtorz_ja_rano_przed_wazna":{"pl":"Powtórz ją rano, przed ważną decyzją albo wtedy, gdy chcesz wrócić do własnego środka.","en":"Repeat it in the morning, before an important decision, or when you want to return to your own center.","es":"Repítela por la mañana, antes de una decisión importante o cuando quieras volver a tu propio centro.","pt":"Repita-a de manhã, antes de uma decisão importante ou quando quiser voltar ao seu próprio centro.","de":"Wiederhole sie morgens, vor einer wichtigen Entscheidung oder wenn du zu deiner eigenen Mitte zurückkehren möchtest.","fr":"Répète-la le matin, avant une décision importante ou quand tu veux revenir à ton propre centre.","it":"Ripetila la mattina, prima di una decisione importante o quando vuoi tornare al tuo centro.","ru":"Повторяйте её утром, перед важным решением или когда хотите вернуться к своему собственному центру.","ar":"كررها في الصباح، قبل قرار مهم أو عندما تريد العودة إلى مركزك الخاص.","ja":"朝、重要な決断の前、または自分の中心に戻りたいときに繰り返してください。","zh":"在早晨、重要决定前，或想回归自我中心时重复它。"},
  "zapisz_w_dzienniku":{"pl":"Zapisz w Dzienniku","en":"Save to Journal","es":"Guardar en Diario","pt":"Salvar no Diário","de":"Im Tagebuch speichern","fr":"Enregistrer dans le journal","it":"Salva nel Diario","ru":"Сохранить в дневник","ar":"حفظ في المجلة","ja":"ジャーナルに保存","zh":"保存到日记"},
  "podziel_sie":{"pl":"Podziel się","en":"Share","es":"Compartir","pt":"Compartilhar","de":"Teilen","fr":"Partager","it":"Condividi","ru":"Поделиться","ar":"مشاركة","ja":"シェア","zh":"分享"},
  "wroc_do_tych_slow_w":{"pl":"Wróć do tych słów w chwili rozproszenia. Trzy wyrazy wystarczą, żeby umysł wrócił do centrum.","en":"Return to these words in moments of distraction. Three words are enough for the mind to return to center.","es":"Vuelve a estas palabras en momentos de distracción. Tres palabras son suficientes para que la mente regrese al centro.","pt":"Volte a estas palavras em momentos de distração. Três palavras são suficientes para a mente retornar ao centro.","de":"Kehre in Momenten der Ablenkung zu diesen Worten zurück. Drei Worte reichen aus, damit der Geist zur Mitte zurückkehrt.","fr":"Reviens à ces mots dans les moments de distraction. Trois mots suffisent pour que l'esprit revienne au centre.","it":"Torna a queste parole nei momenti di distrazione. Tre parole bastano perché la mente torni al centro.","ru":"Возвращайтесь к этим словам в моменты рассеянности. Трёх слов достаточно, чтобы ум вернулся к центру.","ar":"عد إلى هذه الكلمات في لحظات التشتت. ثلاث كلمات تكفي لعودة العقل إلى المركز.","ja":"気が散る瞬間にこれらの言葉に戻ってください。3つの言葉で心は中心に戻れます。","zh":"在分心时回到这些话语。三个词就足以让心灵回归中心。"},
  "praktyka_afirmacji_4_kroki":{"pl":"PRAKTYKA AFIRMACJI — 4 KROKI","en":"AFFIRMATION PRACTICE — 4 STEPS","es":"PRÁCTICA DE AFIRMACIONES — 4 PASOS","pt":"PRÁTICA DE AFIRMAÇÕES — 4 ETAPAS","de":"AFFIRMATIONSPRAXIS — 4 SCHRITTE","fr":"PRATIQUE DES AFFIRMATIONS — 4 ÉTAPES","it":"PRATICA AFFERMAZIONI — 4 PASSI","ru":"ПРАКТИКА АФФИРМАЦИЙ — 4 ШАГА","ar":"ممارسة التأكيدات — 4 خطوات","ja":"アファメーション練習 — 4ステップ","zh":"肯定语练习 — 4步骤"},
  "7_dniowe_wyzwania":{"pl":"7-DNIOWE WYZWANIA","en":"7-DAY CHALLENGES","es":"RETOS DE 7 DÍAS","pt":"DESAFIOS DE 7 DIAS","de":"7-TAGE-CHALLENGES","fr":"DÉFIS 7 JOURS","it":"SFIDE 7 GIORNI","ru":"7-ДНЕВНЫЕ ВЫЗОВЫ","ar":"تحديات 7 أيام","ja":"7日間チャレンジ","zh":"7天挑战"},
  "ulubione_afirmacje_to_te_ktore":{"pl":"Ulubione afirmacje to te, które rezonują dłużej niż dzień. Wróć do nich w trudniejszych chwilach.","en":"Favorite affirmations are those that resonate longer than a day. Return to them in harder moments.","es":"Las afirmaciones favoritas son aquellas que resuenan más que un día. Vuelve a ellas en momentos difíciles.","pt":"As afirmações favoritas são aquelas que ressoam por mais de um dia. Volte a elas em momentos difíceis.","de":"Lieblingsaffirmationen sind jene, die länger als einen Tag nachhallen. Kehre zu ihnen in schwierigeren Momenten zurück.","fr":"Les affirmations préférées sont celles qui résonnent plus d'un jour. Reviens-y dans les moments difficiles.","it":"Le affermazioni preferite sono quelle che risuonano più a lungo di un giorno. Torna a loro nei momenti difficili.","ru":"Любимые аффирмации — те, которые резонируют дольше одного дня. Возвращайтесь к ним в трудные моменты.","ar":"التأكيدات المفضلة هي تلك التي تتردد لأكثر من يوم. عد إليها في اللحظات الصعبة.","ja":"お気に入りのアファメーションは1日以上共鳴するものです。辛い瞬間にそれらに戻ってください。","zh":"最喜欢的肯定语是那些共鸣超过一天的。在困难时刻回到它们。"},
  "udostepnij_karte":{"pl":"Udostępnij kartę","en":"Share card","es":"Compartir tarjeta","pt":"Compartilhar cartão","de":"Karte teilen","fr":"Partager la carte","it":"Condividi scheda","ru":"Поделиться карточкой","ar":"مشاركة البطاقة","ja":"カードをシェア","zh":"分享卡片"},
  "kopiuj":{"pl":"Kopiuj","en":"Copy","es":"Copiar","pt":"Copiar","de":"Kopieren","fr":"Copier","it":"Copia","ru":"Копировать","ar":"نسخ","ja":"コピー","zh":"复制"},
  "jak_pracowac_z_tym_ekranem":{"pl":"Jak pracować z tym ekranem","en":"How to work with this screen","es":"Cómo trabajar con esta pantalla","pt":"Como trabalhar com esta tela","de":"So arbeite mit diesem Bildschirm","fr":"Comment travailler avec cet écran","it":"Come lavorare con questa schermata","ru":"Как работать с этим экраном","ar":"كيفية العمل مع هذه الشاشة","ja":"この画面の使い方","zh":"如何使用此屏幕"},
  "zacznij_od_jednej_afirmacji_ktora":{"pl":"Zacznij od jednej afirmacji, która porusza Cię najmocniej. Powtarzaj ją przez kilka oddechów, a resztę traktuj jak wspierającą sekwencję dla całego dnia.","en":"Start with one affirmation that moves you most. Repeat it through a few breaths, and treat the rest as a supporting sequence for the whole day.","es":"Comienza con una afirmación que te mueva más. Repítela durante algunas respiraciones y trata el resto como una secuencia de apoyo para todo el día.","pt":"Comece com uma afirmação que mais te move. Repita-a por algumas respirações e trate o restante como uma sequência de apoio para o dia todo.","de":"Beginne mit der Affirmation, die dich am stärksten bewegt. Wiederhole sie durch einige Atemzüge hindurch und betrachte den Rest als unterstützende Sequenz für den ganzen Tag.","fr":"Commence par l'affirmation qui te touche le plus. Répète-la pendant quelques respirations et traite le reste comme une séquence de soutien pour toute la journée.","it":"Inizia con l'affermazione che ti tocca di più. Ripetila per alcuni respiri e tratta il resto come una sequenza di supporto per l'intera giornata.","ru":"Начните с аффирмации, которая трогает вас больше всего. Повторяйте её несколько вдохов, а остальные воспринимайте как поддерживающую последовательность на весь день.","ar":"ابدأ بالتأكيد الذي يؤثر فيك أكثر. كرره خلال بعض الأنفاس وعامل الباقي كتسلسل داعم لليوم كله.","ja":"最も心を動かすアファメーションから始めてください。数回の呼吸で繰り返し、残りを一日全体のサポートシークエンスとして扱ってください。","zh":"从最能触动你的肯定语开始。通过几次呼吸重复它，将其余的视为全天的支持序列。"},
  "afirmacje_dla_kogos":{"pl":"Afirmacje dla kogoś","en":"Affirmations for someone","es":"Afirmaciones para alguien","pt":"Afirmações para alguém","de":"Affirmationen für jemanden","fr":"Affirmations pour quelqu'un","it":"Affermazioni per qualcuno","ru":"Аффирмации для кого-то","ar":"تأكيدات لشخص ما","ja":"誰かのためのアファメーション","zh":"为某人准备的肯定语"},
  "wpisz_imie_osoby_dla_ktorej":{"pl":"Wpisz imię osoby, dla której chcesz wygenerować afirmacje.","en":"Enter the name of the person you want to generate affirmations for.","es":"Ingresa el nombre de la persona para quien deseas generar afirmaciones.","pt":"Insira o nome da pessoa para quem deseja gerar afirmações.","de":"Gib den Namen der Person ein, für die du Affirmationen generieren möchtest.","fr":"Entre le nom de la personne pour qui tu veux générer des affirmations.","it":"Inserisci il nome della persona per cui vuoi generare affermazioni.","ru":"Введите имя человека, для которого вы хотите создать аффирмации.","ar":"أدخل اسم الشخص الذي تريد توليد تأكيدات له.","ja":"アファメーションを生成したい人の名前を入力してください。","zh":"输入您想为其生成肯定语的人的姓名。"},
  "generuj_afirmacje":{"pl":"Generuj afirmacje","en":"Generate affirmations","es":"Generar afirmaciones","pt":"Gerar afirmações","de":"Affirmationen generieren","fr":"Générer des affirmations","it":"Genera affermazioni","ru":"Создать аффирмации","ar":"توليد التأكيدات","ja":"アファメーションを生成","zh":"生成肯定语"},
  "anuluj":{"pl":"Anuluj","en":"Cancel","es":"Cancelar","pt":"Cancelar","de":"Abbrechen","fr":"Annuler","it":"Annulla","ru":"Отмена","ar":"إلغاء","ja":"キャンセル","zh":"取消"},
  "twoja_refleksja":{"pl":"Twoja refleksja...","en":"Your reflection...","es":"Tu reflexión...","pt":"Sua reflexão...","de":"Deine Reflexion...","fr":"Ta réflexion...","it":"La tua riflessione...","ru":"Ваша рефлексия...","ar":"تأملاتك...","ja":"あなたの振り返り...","zh":"您的反思..."},
  "imie_osoby":{"pl":"Imię osoby...","en":"Person's name...","es":"Nombre de la persona...","pt":"Nome da pessoa...","de":"Name der Person...","fr":"Nom de la personne...","it":"Nome della persona...","ru":"Имя человека...","ar":"اسم الشخص...","ja":"人の名前...","zh":"人名..."},
  "ton":{"pl":"Ton","en":"Tone","es":"Tono","pt":"Tom","de":"Ton","fr":"Ton","it":"Tono","ru":"Тон","ar":"النبرة","ja":"トーン","zh":"语调"},
  "dlugosc":{"pl":"Długość","en":"Length","es":"Longitud","pt":"Comprimento","de":"Länge","fr":"Longueur","it":"Lunghezza","ru":"Длина","ar":"الطول","ja":"長さ","zh":"长度"},
  "styl":{"pl":"Styl","en":"Style","es":"Estilo","pt":"Estilo","de":"Stil","fr":"Style","it":"Stile","ru":"Стиль","ar":"الأسلوب","ja":"スタイル","zh":"风格"},
  "skopiowano":{"pl":"Skopiowano","en":"Copied","es":"Copiado","pt":"Copiado","de":"Kopiert","fr":"Copié","it":"Copiato","ru":"Скопировано","ar":"تم النسخ","ja":"コピーしました","zh":"已复制"},
  "afirmacja_jest_w_schowku":{"pl":"Afirmacja jest w schowku.","en":"Affirmation is in the clipboard.","es":"La afirmación está en el portapapeles.","pt":"A afirmação está na área de transferência.","de":"Die Affirmation ist in der Zwischenablage.","fr":"L'affirmation est dans le presse-papiers.","it":"L'affermazione è negli appunti.","ru":"Аффирмация в буфере обмена.","ar":"التأكيد موجود في الحافظة.","ja":"アファメーションはクリップボードにあります。","zh":"肯定语已在剪贴板中。"},
  "zapisano":{"pl":"Zapisano","en":"Saved","es":"Guardado","pt":"Salvo","de":"Gespeichert","fr":"Enregistré","it":"Salvato","ru":"Сохранено","ar":"تم الحفظ","ja":"保存しました","zh":"已保存"},
  "afirmacja_trafila_do_twojego_dzienn":{"pl":"Afirmacja trafiła do Twojego dziennika.","en":"Affirmation has been added to your journal.","es":"La afirmación ha sido añadida a tu diario.","pt":"A afirmação foi adicionada ao seu diário.","de":"Die Affirmation wurde in dein Tagebuch aufgenommen.","fr":"L'affirmation a été ajoutée à ton journal.","it":"L'affermazione è stata aggiunta al tuo diario.","ru":"Аффирмация добавлена в ваш дневник.","ar":"تمت إضافة التأكيد إلى مجلتك.","ja":"アファメーションがあなたのジャーナルに追加されました。","zh":"肯定语已添加到您的日记中。"},
},
}

# Inject into language files
langs = ["pl","en","es","pt","de","fr","it","ru","ar","ja","zh"]
counts = {lang: 0 for lang in langs}

for lang in langs:
    data = load(lang)
    for ns, keys in TRANSLATIONS.items():
        if ns not in data:
            data[ns] = {}
        for key, translations in keys.items():
            if key not in data[ns]:
                data[ns][key] = translations[lang]
                counts[lang] += 1
    save(data, lang)

print("Injected:")
for lang, count in counts.items():
    print(f"  {lang}: +{count} keys")
