export interface Ritual {
  id: string;
  title: string;
  category: string;
  duration: string;
  durationMinutes: number;
  difficulty: 'gentle' | 'grounded' | 'ceremonial';
  description: string;
  materials: string[];
  steps: string[];
  checklist: string[];
  safetyNote: string;
  careNote: string;
  idealFor: string[];
  affirmationCategory: 'love' | 'abundance' | 'success' | 'peace';
  bestMoment: string;
}

export const RITUALS: Ritual[] = [
  {
    id: 'r1',
    title: 'Rytuał oczyszczenia i wyciszenia',
    category: 'Cleansing',
    duration: '12 min',
    durationMinutes: 12,
    difficulty: 'gentle',
    description: 'Krótki, ale pełny rytuał przejścia z przeciążenia do regulacji. Nie służy natychmiastowej iluzji ulgi, tylko świadomemu przejściu z pobudzenia do odzyskanego centrum. To praktyka domknięcia hałasu, napięcia i emocjonalnego osadu dnia bez duchowego teatru i bez przymusu perfekcyjnego skupienia.',
    materials: ['Szklanka wody', 'Świeca lub delikatne światło', 'Chwila ciszy'],
    steps: [
      'Nazwij jedno konkretne przeciążenie: hałas, napięcie, lęk, relacyjny ślad albo rozproszenie. Nie bierz wszystkiego naraz i nie próbuj oczyszczać całego życia w jednej praktyce.',
      'Ustaw intencję jednym zdaniem: co ma zostać odłożone, a co ma wrócić do środka jako jakość po rytuale.',
      'Rozluźnij barki, wydłuż wydech i wykonaj trzy spokojne wydechy, jakbyś oddawała lub oddawał nadmiar pobudzenia poza siebie.',
      'Wypij kilka łyków wody w ciszy. Traktuj ten gest jak domywanie napięcia od środka, nie jak techniczny obowiązek.',
      'Przez chwilę zostań bez ruchu i sprawdź, czy ciało potrzebuje bardziej miękkości, ciszy czy domknięcia.',
      'Na końcu nazwij jedno uczucie, które zostawiasz za sobą, i jedno, które chcesz zaprosić do reszty dnia. To zdanie staje się symbolicznym domknięciem rytuału.'
    ],
    checklist: [
      'Przygotuj spokojne miejsce bez pośpiechu i bez kolejnego bodźca w tle',
      'Zapewnij sobie wodę lub ciepły napar, który sygnalizuje ciału powrót do bezpieczeństwa',
      'Po rytuale zapisz jedno słowo opisujące stan ciała i jedno słowo opisujące stan umysłu'
    ],
    safetyNote: 'Jeśli jesteś dziś skrajnie przebodźcowana lub zmęczona, skróć rytuał do oddechu, wody i jednego zdania intencji. Nie forsuj skupienia.',
    careNote: 'To rytuał regulujący, nie test samodyscypliny. Po domknięciu nie wracaj od razu do kolejnego bodźca. Daj ciału kilka minut ciszy, wodę albo krótki zapis tego, co zeszło z barków. Dopiero potem wybierz, czy potrzebujesz afirmacji, dalszego oczyszczania czy po prostu spokojnego końca dnia.',
    idealFor: ['wieczór po ciężkim dniu', 'emocjonalny chaos', 'przed snem'],
    affirmationCategory: 'peace',
    bestMoment: 'Najlepiej działa późnym popołudniem albo wieczorem, kiedy chcesz domknąć napięcie dnia.'
  },
  {
    id: 'r2',
    title: 'Rytuał serca i przyciągania bliskości',
    category: 'Love',
    duration: '18 min',
    durationMinutes: 18,
    difficulty: 'grounded',
    description: 'Praktyka dla relacji, czułości i emocjonalnej prawdy. Nie służy fantazji o idealnej miłości, tylko przywróceniu kontaktu z tym, czego serce naprawdę potrzebuje, żeby wejść w więź bez utraty granic. To rytuał miękki w formie, ale poważny w intencji.',
    materials: ['Kartka lub dziennik', 'Ulubiony zapach lub olejek', 'Spokojna muzyka'],
    steps: [
      'Zamknij oczy i przywołaj relację, w której najbardziej potrzebujesz więcej prawdy, miękkości albo bezpiecznej granicy.',
      'Zapisz trzy jakości, których naprawdę potrzebuje Twoje serce. Nie pisz tego, co brzmi ładnie, tylko to, co brzmi uczciwie.',
      'Sprawdź, czy bardziej potrzebujesz bliskości, rozmowy, spokoju, przeprosin, granicy czy czułego gestu. Nazwij tylko jedno centrum.',
      'Przyłóż dłonie do klatki piersiowej i wypowiedz zdanie, które daje Ci poczucie bezpieczeństwa zamiast romantycznej iluzji.',
      'Na końcu zapisz jeden konkretny gest troski, który możesz dziś skierować do siebie lub drugiej osoby bez przekraczania własnej prawdy. Ten gest jest domknięciem procesu, nie dodatkiem.'
    ],
    checklist: [
      'Przygotuj przestrzeń, w której nikt Ci nie przerywa i nie wymusza szybkiej reakcji',
      'Nazwij jedną prawdziwą potrzebę serca zamiast kilku romantycznych ogólników',
      'Zamknij rytuał konkretnym gestem troski albo wyraźną granicą'
    ],
    safetyNote: 'Jeśli temat relacji uruchamia świeży ból lub stratę, utrzymaj rytuał w obszarze samowspółczucia. Nie zamieniaj go w rozdrapywanie historii.',
    careNote: 'Bliskość zaczyna się od regulacji i prawdy. Po rytuale nie przyspieszaj od razu do kontaktu tylko dlatego, że pojawiła się czułość. Najpierw sprawdź, czy serce potrzebuje rozmowy, granicy, gestu troski czy jednego uczciwego zdania. Ten rytuał działa najlepiej wtedy, gdy miękkość nie zastępuje granic, a czułość nie służy omijaniu trudnej rozmowy.',
    idealFor: ['temat relacji', 'potrzeba czułości', 'otwieranie serca'],
    affirmationCategory: 'love',
    bestMoment: 'Najpełniej pracuje rano lub przed ważną rozmową, gdy chcesz wejść w kontakt z sercem.'
  },
  {
    id: 'r3',
    title: 'Rytuał intencji i ukierunkowania energii',
    category: 'Manifestation',
    duration: '15 min',
    durationMinutes: 15,
    difficulty: 'ceremonial',
    description: 'Rytuał dla dni, w których chcesz odzyskać kierunek i przestać karmić rozproszenie. Łączy intencję z realnym ruchem, tak by symboliczny akt nie kończył się na nastroju. To praktyka decyzji, porządku i odpowiedzialnego wejścia w działanie.',
    materials: ['Notatnik', 'Jedna świeca', 'Symbol celu lub projektu'],
    steps: [
      'Nazwij jedną intencję, która naprawdę ma dziś znaczenie. Tylko jedną. Jeśli pojawiają się trzy naraz, wybierz tę, która zmienia najwięcej.',
      'Zapisz, czego nie będziesz dziś dokarmiać: rozproszenia, lęku, odwlekania albo cudzych priorytetów.',
      'Spójrz na symbol celu i wypowiedz zdanie, które nie motywuje agresją, tylko przywraca sprawczość.',
      'Rozpisz pierwszy ruch na najmniejszy sensowny krok, który możesz wykonać w ciągu najbliższych 24 godzin.',
      'Na końcu nazwij, co będzie znakiem domknięcia tego rytuału: wysłany mail, rozpoczęty projekt, jedna decyzja albo świadome "nie". Bez tego rytuał zostaje tylko ładną intencją.'
    ],
    checklist: [
      'Wybierz jedną intencję zamiast pięciu naraz',
      'Usuń z pola widzenia największy rozpraszacz przed zakończeniem rytuału',
      'Ustal jeden realny krok do wykonania dziś i jeden znak jego domknięcia'
    ],
    safetyNote: 'Nie używaj tego rytuału do podkręcania presji ani zawstydzania siebie za brak produktywności. Jeśli jesteś wyczerpana lub wyczerpany, wybierz wersję krótszą.',
    careNote: 'Manifestacja działa najczyściej wtedy, gdy nie jest desperacją. Najpierw ustaw kierunek, potem rytm i dopiero na końcu tempo. Po rytuale wróć do jednego realnego kroku, zanim pozwolisz, by energia rozproszyła się na pięć innych rzeczy. Domknięciem tej praktyki nie jest poczucie mocy, tylko wykonany pierwszy ruch w świecie.',
    idealFor: ['nowy projekt', 'odzyskanie skupienia', 'początek cyklu'],
    affirmationCategory: 'success',
    bestMoment: 'Najlepiej rano lub na początku tygodnia, gdy chcesz ustawić ton dla swoich działań.'
  }
,
  {
    id: 'r4',
    title: 'Rytuał ochrony i zamknięcia przestrzeni',
    category: 'Protection',
    duration: '10 min',
    durationMinutes: 10,
    difficulty: 'grounded',
    description: 'Praktyka dla momentów, gdy czujesz, że Twoja przestrzeń jest za bardzo otwarta na cudzy chaos, energię lub presję. Nie chodzi o magiczne odpędzanie zagrożenia, tylko o świadome postawienie granicy między tym, co Twoje, a tym, co niesiesz z zewnątrz. Ten rytuał przywraca poczucie centrum i własnego terytorium bez dramatyzmu.',
    materials: ['Spokojna przestrzeń', 'Świeca lub delikatne światło', 'Opcjonalnie: sól w małej misce'],
    steps: [
      'Zatrzymaj się i nazwij dokładnie, co czujesz jako cudze: czyjś lęk, presja, ocena, niezamknięty konflikt albo energetyczny chaos, którego nie zaprosiłaś lub nie zaprosiłeś.',
      'Stojąc lub siedząc wygodnie, poczuj podłogę pod stopami. To jest Twoje terytorium: to, co leży pod Twoimi stopami, należy do Ciebie.',
      'Powoli zrób trzy wydechy, wyobrażając sobie, że z każdym wydechem cofasz z powrotem do siebie to, co Twoje, i oddajesz to, co nie jest Twoje.',
      'Jeśli używasz soli, umieść małą ilość przy wejściu do pokoju jako symbol granicy. To gest, nie magia techniczna. Chodzi o świadome zaznaczenie progu.',
      'Wypowiedz jedno zdanie granicy głośno lub w myśli: coś w stylu "To jest moja przestrzeń. To, co tu wchodzę, służy mnie." Słowa mogą być Twoje, ważne, żeby brzmiały uczciwie.',
      'Zakończ rytuał krótkim skanem ciała: czy barki są niżej, czy oddech jest wolniejszy, czy przestrzeń wokół czuje się bardziej Twoja. To są znaki, że granica została postawiona.'
    ],
    checklist: [
      'Nazwij jedną konkretną energetyczną granicę, którą chcesz postawić',
      'Wykonaj rytuał przed wejściem w sytuację, która historycznie Cię drenuje',
      'Po rytuale obserwuj przez 10 minut, czy ciało sygnalizuje większy spokój'
    ],
    safetyNote: 'Jeśli czujesz silny strach lub dysocjację, zacznij od prostego oddechu i dotyku stóp o podłogę. Rytuał ochrony nie zastąpi terapii przy chronicznym narastającym lęku.',
    careNote: 'Ochrona energetyczna to nie mur, tylko filtr. Po rytuale nie izoluj się kompletnie. Sprawdź, czy po postawieniu granicy możesz bardziej autentycznie wejść w kontakt zamiast się od niego odciąć. Granica służy bliskości, nie unikaniu.',
    idealFor: ['wchodzenie w trudną sytuację', 'po emocjonalnie drenującym kontakcie', 'początek dnia z dużym naporem społecznym'],
    affirmationCategory: 'peace',
    bestMoment: 'Rano przed trudnym spotkaniem lub wieczorem po dniu pełnym cudzych oczekiwań.'
  },
  {
    id: 'r5',
    title: 'Rytuał uwalniania przywiązań i starego śladu',
    category: 'Cleansing',
    duration: '20 min',
    durationMinutes: 20,
    difficulty: 'ceremonial',
    description: 'Głębokie uwolnienie dla momentów, gdy coś z przeszłości nadal żyje w Twoim ciele, myśli lub reakcjach: stara relacja, niedomknięty konflikt, obraz siebie, który nie jest już prawdziwy, albo historia, która Cię drenuje bez Twojej zgody. Ten rytuał nie kasuje przeszłości. Pomaga postawić świadomą granicę między tym, co było, a tym, czym jesteś teraz.',
    materials: ['Kartka do spalenia lub podarcia', 'Długopis', 'Miska lub metalowy pojemnik', 'Świeca'],
    steps: [
      'Usiądź wygodnie i nazwij dokładnie to, co chcesz uwolnić. Nie ogólniki: nie "stary ból", tylko konkretna relacja, konkretna historia, konkretne przekonanie o sobie. Im bardziej precyzyjne, tym mocniejszy rytuał.',
      'Zapisz to na kartce pełnym zdaniem: "Trzymam się [to konkretne], bo [to konkretny powód]. Dzisiaj wybieram, żeby to już nie karmiło mojej teraźniejszości."',
      'Przeczytaj to zdanie głośno. Poczuj opór, jeśli jest. Opór oznacza, że to jest prawdziwe i ważne, nie że rytuał nie działa.',
      'Jeśli masz możliwość i bezpieczne miejsce: spal kartkę, obserwując płomień jako symbol fizycznego zakończenia. Jeśli nie możesz palić: podrzyj kartkę na jak najmniejsze kawałki. Rozproszenie fizyczne jest równie realne symbolicznie.',
      'Po spaleniu lub podarciu wypowiedz zdanie domknięcia: "Widziałam lub widziałem to. Pamiętam to. Nie muszę tego dalej nieść." To rozróżnienie między pamiętaniem a noszeniem jest sercem tego rytuału.',
      'Siedź przez 2-3 minuty w ciszy. Obserwuj, czy ciało czuje choćby minimalne rozluźnienie. Jeśli nie, to też jest informacja: być może ten temat wymaga więcej niż jednej sesji.'
    ],
    checklist: [
      'Nazwij konkretne przywiązanie, nie abstrakcyjną "przeszłość"',
      'Zapisz zdanie z pełną świadomością, że to naprawdę chcesz oddać',
      'Zakończ rytuał spaleniem lub podarciem kartki — fizyczny gest domknięcia jest częścią procesu, nie dekoracją'
    ],
    safetyNote: 'Nie używaj tego rytuału do forsowania emocji, które nie są gotowe. Jeśli pojawia się intensywny ból lub dysocjacja, zatrzymaj się, połóż dłonie na klatce piersiowej i oddychaj. Ten rytuał należy do chwil, gdy czujesz wewnętrzną zgodę, nie nacisk z zewnątrz.',
    careNote: 'Uwolnienie nie oznacza zapomnienia. Po rytuale możesz nadal pamiętać tę osobę, sytuację lub wersję siebie. Pytanie nie brzmi "czy zapomniałem", tylko "czy to nadal steruje moim dniem bez mojej zgody". Jeśli po kilku dniach temat wraca z tą samą siłą, to sygnał, że wymaga głębszej pracy, być może z towarzyszeniem terapeuty.',
    idealFor: ['zakończenie związku lub etapu', 'uwolnienie się od starej narracji o sobie', 'początek nowego cyklu'],
    affirmationCategory: 'peace',
    bestMoment: 'Wieczorem w okolicy nowiu lub pełni księżyca albo w dowolnym momencie, gdy czujesz, że stary ślad ciąży zbyt mocno.'
  },
  {
    id: 'r6',
    title: 'Rytuał poranny i zakorzenienie dnia',
    category: 'Morning',
    duration: '8 min',
    durationMinutes: 8,
    difficulty: 'gentle',
    description: 'Krótka, konkretna praktyka powrotu do siebie przed wejściem w wir dnia. Nie chodzi o duchową inspirację na start, tylko o zatrzymanie się wystarczająco długo, żeby wiedzieć, z jakiego miejsca wchodzisz w dzień. To różnica między dniem reaktywnym a dniem, w którym masz choćby jeden świadomy ruch.',
    materials: ['Szklanka ciepłej wody lub kawy', 'Spokojna chwila przed pierwszym telefonem'],
    steps: [
      'Zanim sięgniesz po telefon, usiądź przez chwilę w ciszy. Jeden oddech. Jedno pytanie: jak czuje się moje ciało dzisiaj? Nie analizuj, tylko poczuj.',
      'Wypij pierwszy łyk czegoś ciepłego powoli, jakby to było jedyne zadanie przez te 30 sekund.',
      'Zadaj sobie jedno pytanie: co jest dzisiaj najważniejsze? Tylko jedno. Jeśli przychodzą cztery naraz, wybierz to, które zmienia najbardziej.',
      'Powiedz to zdanie głośno lub zapisz je: "Dzisiaj najważniejsze jest [to konkretne]." To ustawia radar uwagi.',
      'Sprawdź ciało raz jeszcze: czy masz napięcie w barkach, szczęce, klatce? Oddech przez usta kilka razy, rozluźnienie w barkach, i wchodzisz w dzień nie jako reaktywna maszyna, ale jako osoba, która wie, czym jest jej dzisiejszy rdzeń.'
    ],
    checklist: [
      'Wykonaj przed pierwszym sprawdzeniem telefonu lub mediów',
      'Wybierz jedną intencję, nie listę',
      'Zakończ skanem ciała — przynajmniej 10 sekund ciszy przed wejściem w dzień'
    ],
    safetyNote: 'Jeśli rano jest trudne ze względu na stany lękowe lub depresyjne, skróć rytuał do jednego oddechu i jednego zdania. Nie musisz czuć się dobrze, żeby zrobić jeden świadomy ruch.',
    careNote: 'Ten rytuał działa najlepiej wtedy, gdy nie jest kolejnym punktem na liście zadań. To jest tworzenie podmiotowości przed wejściem w resztę dnia, nie kolejna technika produktywności. Jeśli czujesz opór przed robieniem tego codziennie, rób to gdy naprawdę potrzebujesz, nie przez przymus.',
    idealFor: ['trudne poranki', 'przed ważnym dniem', 'powrót do praktyki po przerwie'],
    affirmationCategory: 'success',
    bestMoment: 'Pierwsze 5-10 minut po przebudzeniu, przed kontaktem z ekranem.'
  },
  {
    id: 'r7',
    title: 'Rytuał ciszy i świadomego niedziałania',
    category: 'Support',
    duration: '15 min',
    durationMinutes: 15,
    difficulty: 'gentle',
    description: 'Praktyka dla momentów, gdy zrobiłeś lub zrobiłaś już wystarczająco dużo i teraz potrzebujesz zregenerować się zamiast dołożyć kolejną praktykę. Ten rytuał nie ma produktu. Jest sam w sobie celem. Pozwolenie sobie na ciszę lub nieproduktywny czas to często najtrudniejszy ruch dla osób, które używają działania jako regulacji emocjonalnej.',
    materials: ['Wygodne miejsce siedzące lub leżące', 'Cisza lub bardzo łagodna muzyka bez słów'],
    steps: [
      'Połóż się lub usiądź tak, żeby ciało czuło się bezpiecznie i wsparte. Nie musisz siedzieć prosto.',
      'Zamknij oczy i przez pierwszą minutę po prostu słuchaj: co słyszy Twoje ciało? Dźwięki z zewnątrz, bicie serca, tempo oddechu.',
      'Jeśli pojawia się myśl "powinienem lub powinnam już coś robić", zauważ ją bez oceny i wróć do słuchania. Ta myśl jest informacją, nie poleceniem.',
      'Przez następne 10 minut pozwól umysłowi wędrować bez kierowania go w żadną stronę. Jeśli pojawia się coś ważnego, to zostanie. Jeśli nie, to też było potrzebne.',
      'Na koniec, zanim wstaniesz, zadaj jedno pytanie: co moje ciało dzisiaj potrzebuje najbardziej? Odpowiedź często przychodzi wtedy, gdy przestajesz szukać.'
    ],
    checklist: [
      'Przygotuj przestrzeń, w której nie będziesz przerywany przez co najmniej 15 minut',
      'Odłóż telefon poza zasięgiem wzroku',
      'Nie oceniaj, czy rytuał się "udał" — cisza zawsze działa'
    ],
    safetyNote: 'Jeśli cisza uruchamia silny niepokój, zacznij od krótszego czasu: 3-5 minut. Cisza nie powinna być torturą. Możesz delikatnie poruszać palcami stóp lub dłońmi, jeżeli potrzebujesz lekkiego dotyku z ciałem.',
    careNote: 'Cisza to nie pustka. To przestrzeń, w której możesz w końcu usłyszeć to, co ignorowałeś lub ignorowałaś przez cały dzień. Po rytuale nie oceniaj, ile "osiągnąłeś". Zamiast tego zauważ, czy ciało jest choć trochę cięższe w dobrym sensie, czyli bardziej zakorzenione.',
    idealFor: ['wypalenie lub przemęczenie', 'po intensywnym tygodniu', 'kiedy czujesz że masz za dużo na głowie'],
    affirmationCategory: 'peace',
    bestMoment: 'Popołudnie lub wczesny wieczór, kiedy dzień już został przeżyty a noc jeszcze nie zaczęła.'
  },
  {
    id: 'r8',
    title: 'Rytuał zamknięcia cyklu i gotowości na nowe',
    category: 'Manifestation',
    duration: '22 min',
    durationMinutes: 22,
    difficulty: 'ceremonial',
    description: 'Dłuższy, bardziej ceremonialny rytuał na momenty przejścia: koniec projektu, związku, etapu życia, roku, miesiąca, sezonu. Nie chodzi o sztuczne świętowanie, tylko o świadome domknięcie tego, co było, zanim wejdziesz w nowy rozdział. Bez domknięcia stary rozdział kontynuuje się w tle nowego i komplikuje go od środka.',
    materials: ['Dziennik lub kartki', 'Dwie świece: jedna do zamknięcia, jedna do otwarcia', 'Opcjonalnie: przedmiot symbolizujący miniony etap'],
    steps: [
      'Usiądź z dziennikiem lub kartkami. Napisz na górze datę i nazwę tego, co domykasz: "Zamykam etap [nazwa]. Zaczął się [kiedy]. Kończy się dzisiaj."',
      'Napisz trzy rzeczy, za które jesteś wdzięczna lub wdzięczny w tym etapie. Nie romantyzuj. Pisz uczciwie nawet o trudnych lekcjach.',
      'Napisz trzy rzeczy, które zostawiasz: przekonania, nawyki, relacje, sposoby reagowania, które należą do etapu, ale już nie do Ciebie.',
      'Zapal pierwszą świecę jako symbol domknięcia. Siedź przez chwilę z tym, co było. Nie pośpieszaj się.',
      'Napisz jedno zdanie o tym, kim chcesz być w nowym rozdziale. Nie co chcesz osiągnąć, tylko kim chcesz być.',
      'Zapal drugą świecę od pierwszej jako symbol kontynuacji i nowego otwarcia.',
      'Zakończ pisaniem jednego małego pierwszego kroku do nowego etapu, który możesz wykonać w ciągu najbliższych 24 godzin. Rytuał najlepiej działa, gdy łączy symboliczne zamknięcie z realnym otwarciem.'
    ],
    checklist: [
      'Wyznacz co najmniej 20 minut bez przerw',
      'Napisz szczerze, nawet jeśli to co zamykasz było trudne lub bolesne',
      'Zakończ rytuał krótkim konkretnym krokiem, nie tylko pięknym zdaniem'
    ],
    safetyNote: 'Jeśli to, co zamykasz, jest związane ze stratą lub traumą, idź własnym tempem. Rytuał można robić etapami przez kilka dni. Nie musisz domknąć wszystkiego naraz.',
    careNote: 'Domknięcie cyklu nie znaczy, że przestajesz odczuwać to, co było. Znaczy, że stwierdzasz: to się naprawdę skończyło i mam prawo iść dalej bez czekania na idealne poczucie gotowości. Gotowość najczęściej przychodzi po pierwszym kroku, nie przed nim.',
    idealFor: ['koniec roku lub sezonu', 'po rozstaniu', 'po zakończeniu projektu lub etapu pracy', 'przed nowym ważnym krokiem'],
    affirmationCategory: 'abundance',
    bestMoment: 'Wieczorem w okolicy końca miesiąca, w okolicy nowiu lub w dowolny dzień, gdy czujesz wyraźne zakończenie etapu.'
  },
  {
    id: 'r9',
    title: 'Rytuał snu i spokojnego wejścia w noc',
    category: 'Sleep',
    duration: '12 min',
    durationMinutes: 12,
    difficulty: 'gentle',
    description: 'Praktyka na granicy między dniem a nocną ciszą. Nie jest to technika zasypiania, tylko świadome zamknięcie dnia, żeby umysł nie kontynuował go w nieskończoność pod przykryciem. Wielu z nas nie zasypia, tylko przestaje udawać, że działa. Ten rytuał robi ten próg świadomym.',
    materials: ['Dziennik lub kartka', 'Delikatne światło lub świeca', 'Cisza lub bardzo łagodna muzyka'],
    steps: [
      'Usiądź na łóżku lub w wygodnym miejscu. Jeszcze nie pod przykryciem. Napisz lub powiedz głośno: "Dziś wydarzyło się [jedno konkretne]." Tylko jedno. Nie podsumowuj całego dnia.',
      'Napisz lub powiedz jedno zdanie wdzięczności. Nie musi być wzniosłe. Może być tak proste jak "ciepła herbata wieczorem" lub "cisza przez 10 minut".',
      'Sprawdź, czy niesiesz jakąś myśl lub emocję, która nie pozwoli Ci odejść. Jeśli tak, zapisz ją: "Jutro zajmę się [tym konkretnym]." To przeniesie ją z umysłu na papier.',
      'Wykonaj trzy powolne oddechy z wydłużonym wydechem: wdech przez 4 sekundy, wydech przez 7. To aktywuje układ przywspółczulny i daje ciału sygnał: czas na ochronny sen.',
      'Połóż się i przez ostatnią minutę skup się tylko na dotyku materaca lub poduszki. Jeśli umysł wraca do myśli, delikatnie wracaj do czucia ciężaru ciała. To nie jest walka z umysłem, tylko łagodne zaproszenie do ciała.'
    ],
    checklist: [
      'Wyłącz ekrany co najmniej 5 minut przed rytuałem',
      'Zapisz "jutrzejszą myśl" zamiast się z nią borykać w nocy',
      'Zakończ rytuał kiedy jeszcze siedzisz, nie gdy już leżysz — przejście jest częścią rytuału'
    ],
    safetyNote: 'Jeśli masz bezsenność strukturalną lub silny lęk nocny, ten rytuał może być uzupełnieniem pracy z terapeutą czy lekarzem. Nie zastąpi interwencji medycznej przy poważnych problemach ze snem.',
    careNote: 'Sen jest odnową, nie nagrodą. Nie musisz "zasługiwać" na sen przez to, że byłaś lub byłeś wystarczająco produktywna lub produktywny. Dobry sen zaczyna się od decyzji, że kończysz dzień, nawet jeżeli coś jest niedokończone.',
    idealFor: ['przed snem', 'trudne zasypianie', 'dni z dużą ilością bodźców', 'po emocjonalnie trudnym dniu'],
    affirmationCategory: 'peace',
    bestMoment: '20-30 minut przed planowanym snem.'
  },
  {
    id: 'r10',
    title: 'Rytuał pełni księżyca',
    category: 'Moon',
    duration: '20 min',
    durationMinutes: 20,
    difficulty: 'ceremonial',
    description: 'Ceremonia mocy pełni — czas, gdy energia księżyca jest na swoim szczycie. Rytuał służy wzmocnieniu intencji, zakończeniu tego, co nie służy, i naładowaniu obiektów symbolicznych. To praktyka wymagająca skupienia i szacunku do cyklu.',
    materials: ['Miska z wodą', 'Biała lub srebrna świeca', 'Kartka z intencjami', 'Opcjonalnie: kryształy lub symbole osobiste'],
    steps: [
      'Ustaw misę z wodą tak, by odbijała światło księżyca (na zewnątrz lub przy oknie). Księżycowa woda to nośnik intencji.',
      'Zapal białą lub srebrną świecę. Chwila ciszy — pozwól ciału zarejestrować, że to jest moment ceremonii, nie rutyna.',
      'Weź kartę z intencjami napisaną kilka dni wcześniej. Przeczytaj ją głośno. Sprawdź, czy to nadal Twoja prawda — jeśli tak, trzymaj to zdanie z pełnym przekonaniem.',
      'Połóż dłonie na wodzie lub nad nią. Wyobraź sobie, że intencja wnika w wodę i księżycowe światło ją wzmacnia. To gest symboliczny, ale symbole mają siłę, gdy są wykonane świadomie.',
      'Na odwrocie kartki napisz jedno przywiązanie, które chcesz puścić w tej pełni. Nie wielkie listy — jedno, konkretne.',
      'Podrap lub złóż kartkę symbolizując uwalnianie. Woda pozostaje jako nośnik intencji — możesz jej użyć do podlania rośliny lub mycia twarzy rano.',
      'Zakończ przez 3 minuty ciszy przy świecy. Obserwuj płomień. Kiedy będziesz gotowa lub gotowy, ugaś świecę z poczuciem zamknięcia.',
    ],
    checklist: [
      'Napisz intencję przed rytuałem — nie improwizuj jej podczas ceremonii',
      'Przygotuj misę z wodą co najmniej godzinę przed — niech nasiąka energią księżyca',
      'Zakończ konkretnym aktem uwalniania, nie tylko intencją'
    ],
    safetyNote: 'Jeśli pełnia wywołuje u Ciebie silne emocje lub bezsenność, skróć rytuał do oddechu, jednej świecy i jednego zdania. Nie musisz robić "pełnej ceremonii" za każdym razem.',
    careNote: 'Pełnia to czas wyraźności, nie presji. Jeśli intencja z kartki nie jest już aktualna — to też jest informacja. Cykl księżyca uczy pokory wobec własnych zmian. Po rytuale nawodnij się i daj sobie noc bez ekranów jeśli możesz.',
    idealFor: ['pełnia księżyca', 'wzmacnianie intencji', 'symboliczne zakończenia'],
    affirmationCategory: 'abundance',
    bestMoment: 'Wieczorem w noc pełni lub dzień przed/po — siła pełni trwa przez 3 dni.'
  },
  {
    id: 'r11',
    title: 'Rytuał ochrony energetycznej',
    category: 'Protection',
    duration: '10 min',
    durationMinutes: 10,
    difficulty: 'gentle',
    description: 'Codzienna tarcza — szybki rytuał dla osób, które dużo pracują z ludźmi, w chaotycznych środowiskach lub mają tendencję do wchłaniania cudzych emocji. Nie chodzi o izolację, lecz o świadomy filtr między sobą a otoczeniem.',
    materials: ['Chwila prywatności', 'Opcjonalnie: jedna świeca lub kadzidło'],
    steps: [
      'Stań lub usiądź wygodnie. Weź jeden głęboki oddech i poczuj granicę swojego ciała — skórę, ubranie, przestrzeń tuż przy sobie.',
      'Wyobraź sobie, że Twoje ciało otacza miękkie, ale wyraźne światło — kolor, który czujesz jako bezpieczny. Nie musisz nic "robić" — wystarczy to zobaczyć w umyśle na kilka sekund.',
      'Powiedz lub pomyśl: "Niosę swoje emocje. Jestem obecna/obecny bez przejęcia cudzego ciężaru." To zdanie może być Twoje — ważne, by było uczciwe.',
      'Sprawdź ciało: czy barki są napięte? Czy szczęka zaciśnięta? Rozluźnij je świadomym gestem. To jest fizyczna część ochrony.',
      'Zakończ jednym oddechem i jednym krokiem do przodu. Granica jest teraz postawiona — nie jako mur, tylko jako świadomy filtr.',
    ],
    checklist: [
      'Wykonaj przed wejściem w wymagające środowisko lub kontakt',
      'Skup się na granicy, nie na odcięciu — ochrona służy obecności, nie izolacji',
      'Wróć do tego rytuału wieczorem jeśli czujesz, że niosłeś za dużo cudzego'
    ],
    safetyNote: 'Jeśli granice osobiste są dla Ciebie trudnym tematem terapeutycznie, traktuj ten rytuał jako uzupełnienie, nie zastępstwo pracy głębszej.',
    careNote: 'Ochrona energetyczna to codzienna higiena, nie jednorazowy akt. Tak jak myjesz zęby, możesz ustawiać granice energetyczne każdego ranka. Z czasem stanie się naturalnym gestem.',
    idealFor: ['przed trudnymi spotkaniami', 'dla osób empatyzujących', 'po drenującym kontakcie'],
    affirmationCategory: 'peace',
    bestMoment: 'Rano przed wyjściem z domu lub przed ważnym spotkaniem.'
  },
  {
    id: 'r12',
    title: 'Rytuał kreatywności i natchnienia',
    category: 'Manifestation',
    duration: '15 min',
    durationMinutes: 15,
    difficulty: 'grounded',
    description: 'Praktyka odblokowująca twórczy przepływ. Dla artystów, twórców, ale też dla każdego, kto czuje, że utknął w powtarzalności i chce przywrócić sobie dostęp do spontaniczności, ciekawości i nowych perspektyw.',
    materials: ['Kartka lub szkicownik', 'Długopis lub ołówek', 'Opcjonalnie: muzyka bez słów'],
    steps: [
      'Przed rozpoczęciem — 3 minuty absolutnej bezczynności. Żadnych telefonów, żadnych zadań. Pozwól umysłowi się nudzić. Nuda to bramka do kreatywności.',
      'Weź kartkę i przez 2 minuty pisz lub rysuj wszystko co przychodzi — bez cenzury, bez oceny, bez logiki. Strumień świadomości to ćwiczenie, nie wypracowanie.',
      'Podkreśl lub zakreśl jeden element z tego, co pojawiło się — obraz, słowo, zdanie. Nie myśl o tym, tylko pozwól ciału wybrać.',
      'Zadaj sobie pytanie: "Co by się stało, gdyby ten element był punktem wyjścia do czegoś nowego?" Nie szukaj odpowiedzi — daj jej się pojawić w ciągu 60 sekund.',
      'Zapisz jedno zdanie nowej idei lub kierunku. Nie musisz jej rozwijać teraz — wystarczy zapisać. Nasiono jest posiane.',
      'Zakończ jednym gestem wdzięczności dla swojej kreatywności — nawet jeśli dziś wydawała się mała. Kreatywność rośnie przez docenianie.',
    ],
    checklist: [
      'Zacznij od nudy — nie przeskakuj do twórczości od razu',
      'Nie oceniaj procesu — wartość jest w przepływie, nie w wyniku',
      'Zapisz choćby jedno zdanie nowej idei zanim zakończysz'
    ],
    safetyNote: 'Jeśli kreatywność łączy się u Ciebie z silnym perfekcjonizmem, zacznij od 5 minut i obniż poprzeczkę maksymalnie. Cel to przepływ, nie dzieło.',
    careNote: 'Kreatywność to mięsień. Nie czekaj na natchnienie — zaproś je przez regularny gest otwarcia. Ten rytuał działa najlepiej, gdy robisz go często, nie perfekcyjnie.',
    idealFor: ['twórcza blokada', 'poszukiwanie nowych pomysłów', 'powrót do pasji'],
    affirmationCategory: 'success',
    bestMoment: 'Rano lub wczesne popołudnie, gdy umysł jest świeży.'
  },
  {
    id: 'r13',
    title: 'Rytuał obfitości i wdzięczności',
    category: 'Abundance',
    duration: '12 min',
    durationMinutes: 12,
    difficulty: 'gentle',
    description: 'Praktyka przestawiająca uwagę z niedoboru na obecność. Nie jest to afirmowanie czegoś nieprawdziwego — to trening dostrzegania tego, co już jest. Wdzięczność to nie naiwność, lecz świadomy wybór kierunku uwagi.',
    materials: ['Dziennik lub kartka', 'Ciepły napój (opcjonalnie)', 'Chwila spokoju'],
    steps: [
      'Zacznij od jednego pytania: co dzisiaj działało? Nie szukaj wielkich rzeczy — herbata, która smakowała dobrze, jedna rozmowa, jeden moment ciszy. Małe i prawdziwe to więcej warte niż wielkie i wyobrażone.',
      'Zapisz trzy konkretne wdzięczności. Każda musi być inaczej sformułowana niż wczoraj — to ćwiczenie dostrzegania, nie rytuał powtarzania formułek.',
      'Przy każdej wdzięczności zatrzymaj się na 10 sekund i naprawdę poczuj ją w ciele. To jest różnica między listą a rytuałem — odczucie, nie tylko słowa.',
      'Teraz jedno pytanie o obfitość: co mam dziś, czego rok temu nie miałam lub nie miałem? To ćwiczenie na perspektywę, nie na porównywanie się z przeszłością.',
      'Zakończ jednym zdaniem intencji: "Widzę to, co mam. Jestem gotowa lub gotowy na więcej z tego samego miejsca obfitości, nie niedoboru."',
    ],
    checklist: [
      'Każda wdzięczność musi być konkretna — nie "zdrowie", tylko "to, że wstałam bez bólu"',
      'Poczuj każdą wdzięczność fizycznie — przynajmniej 10 sekund',
      'Zakończ zdaniem intencji, nie tylko listą'
    ],
    safetyNote: 'Jeśli jesteś dziś w trudnym miejscu emocjonalnie, znajdź tylko jedną małą wdzięczność — nawet oddech, który właśnie wzięłaś lub wziąłeś. To wystarczy.',
    careNote: 'Obfitość nie jest o posiadaniu wszystkiego. Jest o widzeniu tego, co jest. Rytuał wdzięczności działa kumulatywnie — po kilku tygodniach codziennej praktyki zmienia się domyślny kierunek uwagi.',
    idealFor: ['poczucie niedoboru lub braku', 'codzienna praktyka poranna lub wieczorna', 'reset po trudnym dniu'],
    affirmationCategory: 'abundance',
    bestMoment: 'Wieczorem przed snem lub rano jako sposób na start dnia.'
  },
  {
    id: 'r14',
    title: 'Rytuał uzdrowienia ciała i duszy',
    category: 'Healing',
    duration: '18 min',
    durationMinutes: 18,
    difficulty: 'grounded',
    description: 'Praktyka uważności wobec ciała — dla momentów, gdy fizyczne napięcie, ból lub zmęczenie niosą ze sobą emocjonalne echo. Rytuał łączy uważność somatyczną z intencją uzdrowienia w szerokim sensie: nie jako magii, lecz jako świadomego towarzyszenia sobie.',
    materials: ['Wygodne miejsce do leżenia lub siedzenia', 'Cicha przestrzeń', 'Opcjonalnie: ciepła poduszka lub koc'],
    steps: [
      'Połóż się lub usiądź tak, by czuć pełne wsparcie pod plecami lub pośladkami. Ciało ma prawo być wygodne — komfort to nie lenistwo, to bezpieczeństwo.',
      'Zacznij od skanowania ciała od stóp do głowy — bez oceny, tylko obserwacja. Gdzie jest napięcie? Gdzie jest ból? Gdzie jest pusty obszar, który ledwo czujesz?',
      'Skup się na jednym obszarze ciała, który potrzebuje uwagi dziś. Nie musisz wiedzieć dlaczego — wystarczy, że ciało to sygnalizuje.',
      'Przez 3 minuty oddychaj "do" tego miejsca — wyobraź sobie, że każdy wdech niesie do tego obszaru ciepło, przestrzeń i możliwość rozluźnienia. Wydech unosi napięcie.',
      'Powiedz do tego miejsca cicho lub w myślach: "Widzę cię. Jestem tu z tobą." To jest akt towarzyszenia — nie naprawiania, lecz obecności.',
      'Na koniec zapytaj ciało: czego potrzebujesz dziś? Ruch, odpoczynek, ciepło, woda, kontakt? Odpowiedź często jest prosta i konkretna. Zrób to po rytuale.',
    ],
    checklist: [
      'Nie pomijaj skanowania ciała — to brama do reszty rytuału',
      'Nie próbuj naprawić bólu — wystarczy być z nim świadomie',
      'Po rytuale wykonaj jedną małą konkretną troskę o ciało'
    ],
    safetyNote: 'Ten rytuał nie zastępuje pomocy medycznej. Jeśli ból jest przewlekły lub intensywny, skonsultuj się z lekarzem. Rytuał może być uzupełnieniem opieki, nie jej substytutem.',
    careNote: 'Ciało pamięta wszystko, co przeżyłaś lub przeżyłeś. Uzdrowienie zaczyna się od zauważenia, a nie od ignorowania. Regularny kontakt z własnym ciałem przez rytuał buduje interocepcję — zdolność do słyszenia sygnałów zanim staną się krzykiem.',
    idealFor: ['fizyczne napięcie lub ból', 'po chorobie lub intensywnym wysiłku', 'głębszy kontakt z ciałem'],
    affirmationCategory: 'peace',
    bestMoment: 'Wieczorem lub w każdym momencie, gdy czujesz, że ciało woła o uwagę.'
  },
  {
    id: 'r15',
    title: 'Rytuał nowego początku',
    category: 'Moon',
    duration: '15 min',
    durationMinutes: 15,
    difficulty: 'ceremonial',
    description: 'Ceremonia nowiu — czas ciemności i nasion. Nów księżyca to energetyczny moment siewu: intencje zasadzone dziś mają moc kiełkowania przez cały cykl. Rytuał skupia się na precyzji zamiaru i odwadze wejścia w nieznane.',
    materials: ['Czarna lub ciemna świeca', 'Dziennik', 'Opcjonalnie: nasiono lub kamień jako symbol'],
    steps: [
      'Usiądź w ciemności lub przy minimalnym oświetleniu. Nów to czas ciszy przed nowym cyklem — pozwól sobie być w tej ciemności przez chwilę bez potrzeby jej rozjaśniania.',
      'Zadaj sobie pytanie: co chcę zasadzić w tym cyklu? Jedna intencja, jedna jakość, jeden kierunek. Nie lista życzeń — jedno nasiono, starannie wybrane.',
      'Zapisz tę intencję tak, jakbyś pisała lub pisał list do siebie na koniec cyklu (za ok. 28 dni). Co chcesz, żeby się wydarzyło? Kim chcesz być?',
      'Zapal świecę jako symbol tego, co zaczyna rosnąć w ciemności. Ciemność to nie nieobecność — to przestrzeń przed formą.',
      'Trzymaj w dłoniach nasiono lub kamień i wyobraź sobie, że wchłania intencję. To nie magia — to gest kotwiczący zamiar w rzeczywistości fizycznej.',
      'Zamknij rytuał jednym zdaniem ślubu sobie samej lub sobie samemu: co zrobisz w tym cyklu konkretnego, by iść w stronę tej intencji? Jedno działanie, jeden krok.',
    ],
    checklist: [
      'Wybierz jedną intencję — nie kilka. Precyzja to siła nowiu',
      'Napisz ją tak, by za 28 dni można ją było sprawdzić',
      'Zakończ konkretnym zobowiązaniem do działania'
    ],
    safetyNote: 'Jeśli nów przynosi Ci uczucie pustki lub smutku, to naturalne. Ciemność ma swoje miejsce w cyklu. Skróć rytuał do jednego oddechu i jednej intencji jeśli potrzebujesz.',
    careNote: 'Nów to nie czas na wielkie działania — to czas na siew. Działania przyjdą podczas rosnącego księżyca. Daj sobie pozwolenie na powolne wchodzenie w nowy cykl. Nasiono potrzebuje ciemności zanim wyjdzie na światło.',
    idealFor: ['nów księżyca', 'nowe projekty lub etapy', 'siew intencji na cały cykl'],
    affirmationCategory: 'success',
    bestMoment: 'W noc nowiu lub dzień po — gdy ciemność jest najgłębsza.'
  },
  {
    id: 'r16',
    title: 'Rytuał Pełni Księżyca',
    category: 'Moon',
    duration: '40 min',
    durationMinutes: 40,
    difficulty: 'ceremonial',
    description: 'Pełnia to czas zbierania plonów intencji zasadzonych w nów. Rytuał pomaga świadomie przyjąć energie pełni — wzmocnić to, co rozkwita, i puścić to, co hamuje wzrost.',
    materials: ['Biała świeca', 'Miska z wodą', 'Kartka i długopis'],
    steps: [
      'Usiądź w miejscu, gdzie widzisz księżyc. Pełnia nie wymaga jasnego nieba — działa w każdych warunkach. Zapal białą świecę jako punkt skupienia.',
      'Przypomnij sobie intencję lub pragnienie zasadzone podczas nowiu. Jeśli nie pamiętasz — zapytaj siebie, co rosło w twoim życiu bez twojej kontroli.',
      'Postaw miskę z wodą przed sobą. Wyobraź sobie, że woda przyjmuje światło pełni. Patrz na powierzchnię wody przez chwilę — co widzisz, co czujesz?',
      'Napisz na kartce jedno zdanie: Jestem gotowa lub gotowy puścić. Bądź konkretna lub konkretny. Co hamuje twój wzrost?',
      'Spal lub podrzyj kartkę jako gest uwolnienia. Jeśli nie możesz jej spalić — zanurz ją w wodzie i obserwuj jak pismo się rozmazuje.',
      'Zostajź z wodą przez kilka minut. Podziękuj cyklowi, który minął — co zabrał, co przyniósł. Wylej wodę na ziemię ze świadomym zamiarem.',
    ],
    checklist: [
      'Przypomnij sobie intencję z nowiu lub zidentyfikuj, co rozkwitło w tym cyklu',
      'Napisz jedno konkretne zdanie o tym, co chcesz puścić',
      'Wykonaj gest uwolnienia — spal, podrzyj lub zanurz kartkę',
    ],
    safetyNote: 'Pełnia wzmacnia emocje. Jeśli czujesz się przytłoczona lub przytłoczony, skróć Rytuał do trzech oddechów i jednej wdzięczności.',
    careNote: 'Pełnia to szczyt energii w cyklu księżycowym. Co zostaje odpuśczone teraz, traci swoją energetyczną kotwicę w twoim życiu.',
    idealFor: ['noc pełni księżyca', 'uwalnianie blokad', 'domknięcie cyklu', 'wzmocnienie intencji'],
    affirmationCategory: 'abundance',
    bestMoment: 'Noc pełni księżyca, najlepiej na zewnątrz lub przy oknie.',
  },
  {
    id: 'r17',
    title: 'Rytuał Ochrony Energetycznej',
    category: 'Protection',
    duration: '20 min',
    durationMinutes: 20,
    difficulty: 'gentle',
    description: 'Praktyka tworzenia energetycznej ochrony wokół siebie. Nie jako zamknięcie się na świat, ale jako wyraźne postawienie granic — co wpuszczasz do swojej przestrzeni, a czego nie.',
    materials: ['Biała świeca', 'Czarna turmalina (opcjonalnie)'],
    steps: [
      'Usiądź w wygodnej pozycji. Zapal białą świecę. Przez chwilę sidź w ciszy i poczuj obecną energię swojego ciała — bez oceny. Gdzie jesteś teraz?',
      'Weź trzy głębokie oddechy. Przy każdym wydechu wyobraź sobie, że uwalniasz wszelką energię, która nie jest twoja — emocje innych, cudze oczekiwania, napięcia z otoczenia.',
      'Wyobraź sobie, że z twojego centrum promieniuje złote lub białe światło. Powoli rozszerza się wokół ciebie, tworząc lśniącą powłokę na odległość wyciągniętych rąk.',
      'Powiedz lub pomyśl: Ta przestrzeń należy do mnie. Wpuszczam to, co służy mojemu dobrostanowi. Odsyłam z miłością to, co nie jest moje.',
      'Jeśli masz czarną tormalinę, trzymaj ją w dłoni i poczuj jej ciężar jako kotwicę granic. Kamień symbolizuje granicę materialną.',
      'Zakończ świadomym gestem zamknięcia — skrzyżowanie dłoni na sercu i jedno zdanie: Jestem chroniona lub chroniony i otwarty lub otwarta na to, co dobre.',
    ],
    checklist: [
      'Wykonaj oddechowe oczyszczanie przed budowaniem ochrony',
      'Wizualizuj powłokę ochronną ze szczegółami — kolor, gęstość, rozmiar',
      'Zakończ afirmacją granic — słowa mają moc ceremonialną',
    ],
    safetyNote: 'Ochrona energetyczna nie jest izolacją. Jeśli czujesz, że coraz bardziej się zamykasz na innych — warto to omówić z terapeutą lub osobą zaufaną.',
    careNote: 'Granice energetyczne wymagają regularnego odnawiania. Rytuał działa najlepiej jako codzienna poranna praktyka — 5 minut wystarczy po opanowaniu procesu.',
    idealFor: ['rano przed wyjściem z domu', 'przed trudnymi rozmowami', 'po przebywaniu w energetycznie wyczerpującym miejscu'],
    affirmationCategory: 'peace',
    bestMoment: 'Rano przed wyjściem lub wieczorem po wymagającym dniu.',
  },
  {
    id: 'r18',
    title: 'Rytuał Kreatywności i Natchnienia',
    category: 'Creativity',
    duration: '30 min',
    durationMinutes: 30,
    difficulty: 'gentle',
    description: 'Gdy kreatywność wydaje się zablokowana, ten Rytuał pomaga usunąć wewnętrzne przeszkody i ponownie połączyć się z przepływem twórczej energii — niezależnie od dziedziny.',
    materials: ['Pomarańczowa lub żółta świeca', 'Ulubione narzędzie twórcze'],
    steps: [
      'Zacznij od pytania bez oceniania: co ostatnio blokuje mój twórczy przepływ? Nie szukaj właściwej odpowiedzi. Pierwsza myśl jest zazwyczaj trafna.',
      'Zapal pomarańczową lub żółtą świecę. Te barwy aktywują energię sakralnej i słonecznej kreatywności. Patrz na płomień przez minutę w ciszy.',
      'Weź ulubione narzędzie twórcze do rąk — pędzel, pióro, instrument, cokolwiek. Trzymaj je bez zamiaru tworzenia czegoś konkretnego.',
      'Przez 10 minut twórz bez celu i bez oceny. Jeśli piszesz — pisz nonsens. Jeśli rysujesz — rysuj kształty bez sensu. Mózg twórczy budzi się przez zabawę.',
      'Zatrzymaj się i zapytaj: co czuję teraz w ciele po tej swobodnej twórczości? Czy jest więcej lekkoci, oddechu, przestrzeni?',
      'Zakończ jednym zdaniem intencji twórczej — nie efektu, lecz jakości: W moim tworzeniu szukam radości, nie perfekcji.',
    ],
    checklist: [
      'Twórz bez celu przez przynajmniej 10 minut — to kluczowy krok, nie można go skrócić',
      'Nie oceniaj tego, co powstało podczas swobodnej fazy',
      'Zakończ intencją jakości, nie efektu',
    ],
    safetyNote: 'Jeśli blokada twórcza jest głęboka i długotrwała, może towarzyszyć jej coś większego — zmęczenie, depresja. Warto to wtedy omówić z kimś bliskim.',
    careNote: 'Kreatywność to nie talent — to stan dostępu do siebie. Regularny Rytuał twórczy bez presji efektu odbudowuje ten dostęp.',
    idealFor: ['blokada twórcza', 'przed pracą twórczą', 'odblokowanie po długiej przerwie'],
    affirmationCategory: 'success',
    bestMoment: 'Przed pracą twórczą lub gdy czujesz, że inspiracja znikła.',
  },
  {
    id: 'r19',
    title: 'Rytuał Obfitości i Wdzięczności',
    category: 'Abundance',
    duration: '25 min',
    durationMinutes: 25,
    difficulty: 'gentle',
    description: 'Obfitość nie jest tylko sprawą finansów. Ten Rytuał otwiera na szersze doświadczenie dostatku — w relacjach, zdrowiu, czasie, możliwościach — i zakorzeniony jest w głębokiej wdzięczności za to, co już jest.',
    materials: ['Zielona świeca', 'Moneta lub zielony kamień', 'Dziennik wdzięczności'],
    steps: [
      'Zapal zieloną świecę i połóż przed sobą monetę lub zielony kamień. Zieleń i metal to energie ziemi i obfitości — ich obecność w przestrzeni nie jest przypadkowa.',
      'Zadaj sobie pytanie: w jakich obszarach życia mam już więcej, niż zdaję sobie sprawę? Nie mów o brakach — tylko o tym, co jest. Daj sobie 3 minuty.',
      'Otwórz dziennik i napisz pięć form obfitości w swoim życiu, które nie są finansowe: czas, relacje, zdrowie, wiedza, chwile radości.',
      'Weź monetę lub kamień do ręki i poczuj jego ciężar. Wyobraź sobie, że wchłania twoją wdzięczność. Powiedz głośno: Widzę to, co mam. Jestem w obfitości.',
      'Napisz jedno zdanie o tym, czego chciałabyś lub chciałbyś więcej — nie z miejsca braku, ale jako rozszerzenie tego, co już jest.',
      'Zostaw monetę lub kamień przy świecy do jej zgaśnięcia. To gest kotwiczący intencję obfitości w przestrzeni fizycznej.',
    ],
    checklist: [
      'Lista pięciu form niepieniężnej obfitości musi być konkretna — nie ogólna',
      'Weź przedmiot do ręki i poczuj go fizycznie — to akt, nie tylko myśl',
      'Zakończ zdaniem chcenia z miejsca obfitości, nie niedoboru',
    ],
    safetyNote: 'Jeśli trudno ci znaleźć cokolwiek na liście obfitości, to ważny sygnał emocjonalny. Skup się na jednej małej dobrej rzeczy — to wystarczy na start.',
    careNote: 'Obfitość zaczyna się od percepcji. Rytuał wdzięczności przeprogramowuje domyślny filtr uwagi z niedoboru na dostrzeganie. Po 21 dniach regularnej praktyki perspektywa zmienia się trwale.',
    idealFor: ['poczucie finansowego lub emocjonalnego niedoboru', 'czwartkowy wieczór', 'podczas rosnącego księżyca'],
    affirmationCategory: 'abundance',
    bestMoment: 'Czwartkowy wieczór lub podczas rosnącego księżyca.',
  },
  {
    id: 'r20',
    title: 'Rytuał Uzdrowienia Ciała i Duszy',
    category: 'Healing',
    duration: '45 min',
    durationMinutes: 45,
    difficulty: 'grounded',
    description: 'Holistyczna praktyka łącząca oddech, intencję i świadomość ciała. Kieruje uzdrawiającą uwagę do miejsc, które proszą o wsparcie — czy to bólu fizycznego, emocjonalnego, czy energetycznego wyczerpania.',
    materials: ['Niebieska lub biała świeca', 'Kadzidło eukaliptusowe lub lawendowe'],
    steps: [
      'Zapal kadzidło eukaliptusowe lub lawendowe i pozwól dymowi wypełnić przestrzeń. Eukaliptus oczyszcza, lawenda uspokaja — wybierz to, czego potrzebujesz dziś bardziej.',
      'Połóż się w wygodnej pozycji. Zacznij od skanowania ciała od stóp do korony głowy. Nie naprawiaj, nie analizuj — tylko notuj, gdzie jest napięcie, ciepło, ból lub pustka.',
      'Wybierz jedno miejsce w ciele, które woła o uwagę. Skup tam całą swoją czułą uwagę — jakbyś przynosiło temu miejscu ciepłe światło.',
      'Przez 5 minut oddychaj celowo: wdech przez nos niesie uzdrawiające światło do wybranego miejsca. Wydech — napięcie i ból wypływają na zewnątrz.',
      'Powiedz do tego miejsca: Jestem tu. Nie musisz walczyć sam lub sama. Niosę ci uwagę. To jest akt głębokiej autotroski — nie magii, lecz obecności.',
      'Po oddechu powoli rozszerz uwagę na całe ciało. Czego teraz potrzebuje? Ruch, odpoczynek, jedzenie, kontakt? Zapisz odpowiedź i wykonaj ją po rytuale.',
    ],
    checklist: [
      'Nie pomijaj skanowania ciała — to diagnoza przed leczeniem',
      'Bądź z bólem lub napięciem w obecności, nie próbuj go natychmiastowo usunąć',
      'Wykonaj po rytuale jedną konkretną troskę o ciało — odpoczynek, wodę, ruch',
    ],
    safetyNote: 'Ten Rytuał nie zastępuje pomocy medycznej. Przy przewlekłym bólu lub poważnych objawach skonsultuj się z lekarzem. Rytuał jest uzupełnieniem troski, nie jej substytutem.',
    careNote: 'Ciało jest najstarszym archiwum twojego życia. Uzdrowienie zaczyna się od bycia świadkiem własnego ciała — bez wymuszania zmian, z czułą uwagą.',
    idealFor: ['fizyczne napięcie lub ból', 'po chorobie lub intensywnym wysiłku', 'głębszy kontakt z ciałem', 'wieczorna regeneracja'],
    affirmationCategory: 'peace',
    bestMoment: 'Wieczór lub każdy moment, gdy ciało sygnalizuje potrzebę troski.',
  },
  {
    id: 'r21',
    title: 'Rytuał Nowego Początku',
    category: 'Moon',
    duration: '30 min',
    durationMinutes: 30,
    difficulty: 'ceremonial',
    description: 'Nów Księżyca to najlepszy czas na sadzenie intencji. Ten Rytuał pomaga świadomie wejść w nowy cykl — z jasną wizją, otwartym sercem i gotowością do działania od nowa.',
    materials: ['Czarna lub granatowa świeca', 'Dziennik', 'Długopis'],
    steps: [
      'Usiądź w ciemności lub przy minimalnym świetle. Nów to czas przed formą — przestrzeń pełna potencjału, który jeszcze nie ma kształtu. Pozwól sobie być w tej ciemności chwilę.',
      'Zapal czarną lub granatową świecę. Patrz na płomień i zapytaj siebie: co chcę zasadzić w nowym cyklu? Jedno pragnienie, jedna intencja, jeden kierunek.',
      'Otwórz dziennik i napisz intencję tak, jakbyś pisała lub pisał do siebie za 28 dni: co chcesz, żeby się wydarzyło? Jak chcesz się czuć?',
      'Napisz jedno konkretne działanie — małe, wykonalne, realne — które podejmiesz w ciągu 48 godzin jako pierwszy krok w stronę tej intencji.',
      'Połóż dłonie na dzienniku i poczuj ciepło. Wyobraź sobie, że intencja przechodzi z myśli w materię przez ten gest. Oddech, spokój, obecność.',
      'Zamknij Rytuał słowami: Zasiewam w ciemności. Ufam cyklowi. Jestem gotowa lub gotowy na nowy początek. Ugaś świecę i wróć do dziennika za 28 dni.',
    ],
    checklist: [
      'Jedna intencja — nie lista. Precyzja to siła nowiu',
      'Napisz intencję z perspektywy przyszłości — jak chcę być, nie co chcę mieć',
      'Zidentyfikuj jeden konkretny krok działania w ciągu 48 godzin',
    ],
    safetyNote: 'Jeśli nów przynosi smutek lub pustkę, to naturalna część cyklu. Skróć Rytuał do jednego oddechu i jednej intencji. Ciemność jest bezpieczna.',
    careNote: 'Nów to czas ciszy i siewu, nie działania. Działania przyjdą z rosnącym księżycem. Ten Rytuał wyznacza kierunek — reszta jest wzrostem, który dzieje się sam, gdy intencja jest czysta.',
    idealFor: ['nów księżyca', 'nowy etap lub projekt', 'siew intencji na cały cykl księżycowy'],
    affirmationCategory: 'success',
    bestMoment: 'Noc nowiu księżyca lub dzień po — gdy ciemność jest najgłębsza.',
  },
  {
    id: 'r22',
    title: 'Rytuał Transformacji Wzorca',
    category: 'Transformation',
    duration: '25 min',
    durationMinutes: 25,
    difficulty: 'ceremonial',
    description: 'Głęboka praca z jednym powtarzającym się wzorcem, przekonaniem lub reakcją, która nie służy Ci już. Rytuał inicjuje świadomą transformację poprzez nazwanie, zrozumienie i symboliczne pożegnanie starego sposobu bycia.',
    materials: ['Kartka papieru', 'Długopis', 'Ogień lub miska z wodą'],
    steps: [
      'Usiądź w ciszy i nazwij jeden wzorzec, który chcesz zmienić. Bądź konkretna lub konkretny: nie "chcę być lepszym człowiekiem", tylko "chcę przestać reagować gniewem, gdy czuję się niezrozumiany".',
      'Napisz ten wzorzec na kartce. Dopisz: kiedy zaczął? Co mu służyło? Co dziś przez niego tracisz?',
      'Napisz zdanie zrozumienia: "Ten wzorzec chronił mnie, gdy... Dziękuję mu za ochronę i teraz wybieram inaczej."',
      'Napisz nowy wzorzec: jedno zdanie opisujące, jak chcesz reagować w przyszłości. Konkretnie i uczciwie.',
      'Symbolicznie pożegnaj stary wzorzec: spal kartkę w bezpieczny sposób lub rozmoknij ją w wodzie. Patrz jak się rozpuszcza.',
      'Zamknij rytuał oddechem i jednym zdaniem potwierdzenia: "Wybieram transformację świadomie i z szacunkiem dla drogi, jaką przeszłam lub przeszedłem."',
    ],
    checklist: ['Jeden wzorzec — nie lista', 'Zdanie zrozumienia przed zdaniem zmiany', 'Symboliczny akt zakończenia stary wzorzec'],
    safetyNote: 'Jeśli wzorzec wiąże się z traumą, nie rób tego rytuału samodzielnie. Poszukaj wsparcia terapeutycznego.',
    careNote: 'Transformacja to proces, nie moment. Ten rytuał sieje ziarno zmiany — reszta kiełkuje w czasie i działaniu.',
    idealFor: ['chęć zmiany nawyku', 'praca z przekonaniami', 'przełomowy moment'],
    affirmationCategory: 'success',
    bestMoment: 'Pełnia księżyca lub przełomowy moment życiowy.',
  },
  {
    id: 'r23',
    title: 'Rytuał Puszczania i Odrodzenia',
    category: 'Transformation',
    duration: '20 min',
    durationMinutes: 20,
    difficulty: 'grounded',
    description: 'Ceremonia świadomego puszczania tego, co było. Przeszłości, relacji, wersji siebie, które przestały być prawdziwe. Rytuał przynosi spokój, nie wymazanie — transformuje trzymanie w uwolnienie.',
    materials: ['Biała świeca', 'Dziennik', 'Spokojne miejsce'],
    steps: [
      'Zapal białą świecę. Białe światło symbolizuje przestrzeń między starym a nowym.',
      'Napisz wszystko, co chcesz puścić: emocje, przekonania, relacje, wersje siebie. Pisz bez cenzury.',
      'Przeczytaj listę na głos. Każda pozycja zakończ słowami: "Widzę cię. Rozumiem cię. Puszczam cię."',
      'Zamknij dziennik. Siedź przez 5 minut w ciszy — w przestrzeni między tym, co było, a tym, co się staje.',
      'Napisz trzy słowa opisujące to, kogo chcesz teraz być. Nie listę cech — trzy żywe słowa.',
      'Ugaś świecę z wdzięcznością za to, co było, i otwartością na to, co nadchodzi.',
    ],
    checklist: ['Pisz bez cenzury', 'Czytaj głośno — głos ma moc', 'Zostań w ciszy po zamknięciu listy'],
    safetyNote: 'Puszczanie może wywołać silne emocje. To normalne. Miej pod ręką wodę i czas na spokojne przebudzenie.',
    careNote: 'Rytuał puszczania nie jest wymazywaniem. To akceptacja, że coś spełniło swój czas.',
    idealFor: ['zakończenie rozdziału', 'po rozstaniu', 'zmiana etapu życia'],
    affirmationCategory: 'peace',
    bestMoment: 'Ostatni dzień miesiąca, jesień lub czas po pełni księżyca.',
  },
  {
    id: 'r24',
    title: 'Rytuał Otwierania Intuicji',
    category: 'Vision',
    duration: '18 min',
    durationMinutes: 18,
    difficulty: 'gentle',
    description: 'Praktyka dla tych, którzy chcą wzmocnić kontakt z wewnętrznym głosem prowadzenia. Intuicja nie krzyczy — szepce. Ten rytuał uczy ciszy, w której szept staje się słyszalny.',
    materials: ['Fioletowa lub granatowa świeca', 'Dziennik', 'Kadzidło szałwii lub frankincense'],
    steps: [
      'Usiądź w ciszy i zapal kadzidło. Zamknij oczy i weź pięć powolnych oddechów, wydłużając każdy wydech.',
      'Zapytaj siebie: "Co wiem, ale się boję wiedzieć?" Zostań z pytaniem bez szukania odpowiedzi przez dwie minuty.',
      'Otwórz oczy i zacznij pisać. Pisz przez 7 minut bez zatrzymywania się — cokolwiek przychodzi. To strumień świadomości, nie esej.',
      'Przeczytaj to, co napisałaś lub napisałeś. Podkreśl trzy zdania lub słowa, które "przeskakują" — te, które czujesz, nie tylko rozumiesz.',
      'Wróć do tych trzech zdań i zapytaj: "Co ta intuicja chce mi powiedzieć?"',
      'Zamknij rytuał jednym zdaniem prowadzenia dla siebie na dziś. Zapisz je na osobnej kartce i umieść w widocznym miejscu.',
    ],
    checklist: ['Pisz bez zatrzymywania i cenzury', 'Ufaj podkreśleniom, nie analizie', 'Jedno zdanie prowadzenia po rytuale'],
    safetyNote: 'Jeśli intuicja przynosi trudne przeczucia, nie ignoruj ich. Daj sobie czas na zweryfikowanie z rzeczywistością.',
    careNote: 'Intuicja to mięsień. Im częściej jej słuchasz, tym wyraźniej mówi.',
    idealFor: ['decyzyjny moment', 'przed ważnym krokiem', 'wzmacnianie prowadzenia'],
    affirmationCategory: 'success',
    bestMoment: 'Poranny spokój lub późny wieczór, gdy umysł jest mniej hałaśliwy.',
  },
  {
    id: 'r25',
    title: 'Rytuał Wizji i Jasności Celu',
    category: 'Vision',
    duration: '30 min',
    durationMinutes: 30,
    difficulty: 'grounded',
    description: 'Ceremonia wychodzenia poza codzienność i oglądania życia z lotu ptaka. Pozwala zobaczyć, gdzie naprawdę idzie Twoja energia, co naprawdę chcesz tworzyć i ku czemu Twoja dusza naprawdę zmierza.',
    materials: ['Duże białe płótno lub kartka A3', 'Kolorowe pisaki lub kredki', 'Cicha muzyka'],
    steps: [
      'Połóż przed sobą dużą kartę. To mapa Twojego wewnętrznego krajobrazu.',
      'Napisz pośrodku swoje imię lub słowo, które dziś opisuje Twoje centrum.',
      'Przez 10 minut rysuj lub pisz wokół centrum: czego pragniesz? Co Cię dotyka? Co chcesz stworzyć? Co chcesz zmienić? Nie planuj — pozwól ręce prowadzić.',
      'Oglądaj mapę z dystansu. Co jest największe? Najczęściej się powtarza? Co pojawia się niespodziewanie?',
      'Wybierz jeden temat z mapy, który rezonuje najsilniej. Zapisz trzy kroki ku temu tematowi.',
      'Zamknij rytuał zdaniem: "Widzę kierunek. Ufam sobie. Zaczynam od małego i pewnego kroku."',
    ],
    checklist: ['Nie cenzuruj mapy', 'Ogladaj z dystansu — jak obraz, nie plan', 'Trzy konkretne kroki ku jednej wizji'],
    safetyNote: 'Jeśli mapa przynosi przytłoczenie, skup się tylko na jednym elemencie. Wizja to kompas, nie nakaz.',
    careNote: 'Wizja bez działania to sen. Działanie bez wizji to chaotyczny wysiłek. Ten rytuał łączy obie siły.',
    idealFor: ['planowanie roku lub nowego etapu', 'utrata kierunku', 'wzmacnianie celu'],
    affirmationCategory: 'success',
    bestMoment: 'Nowy rok, nów księżyca lub moment przełomu.',
  },
  {
    id: 'r26',
    title: 'Rytuał Nowego Początku',
    category: 'NewBeginning',
    duration: '22 min',
    durationMinutes: 22,
    difficulty: 'gentle',
    description: 'Ceremonia świadomego wejścia w nowy etap. Nie wymaga dramatycznych gestów — wymaga uczciwości i intencji. To rytuał dla osób, które stoją na progu czegoś nowego i chcą wejść w to z otwartym sercem.',
    materials: ['Świeże kwiaty lub zielona roślina', 'Dziennik', 'Szklanka świeżej wody'],
    steps: [
      'Usiądź przy roślinach lub kwiatach — symbolu wzrostu i nowego życia. Weź trzy głębokie oddechy.',
      'Napisz: "Kończę rozdział, w którym..." (opisz co masz za sobą — uczciwie i bez oceniania).',
      'Napisz: "Zaczynam rozdział, w którym chcę..." (opisz nie sukcesy, ale jakość istnienia — jak chcesz się czuć, kim chcesz być).',
      'Wypij szklankę wody ze świadomością: czyszczę to, co było i tworzę miejsce na nowe.',
      'Napisz jedno zdanie intencji dla nowego rozdziału. Jedno zdanie, które jest uczciwe i prawdziwe dla Ciebie.',
      'Zamknij dziennik i dotknij rośliny lub kwiatów. Powiedz: "Zaczynam. Jestem gotowa lub gotowy."',
    ],
    checklist: ['Uczciwy opis tego, co kończy', 'Intencja opisuje jakość bycia, nie listę celów', 'Prosty symboliczny gest zamknięcia'],
    safetyNote: 'Nowe początki bywają lękowe. To normalne. Rytuał nie usuwa lęku — pomaga go uhonorować i mimo wszystko wejść.',
    careNote: 'Każdy nowy początek jest małą odwagą. Ten rytuał świętuje ten akt.',
    idealFor: ['zmiana pracy', 'nowe mieszkanie', 'koniec związku', 'nowy etap w życiu'],
    affirmationCategory: 'success',
    bestMoment: 'Pierwszy dzień miesiąca, po ważnej decyzji lub w urodziny.',
  },
  {
    id: 'r27',
    title: 'Rytuał Pierwszego Kroku',
    category: 'NewBeginning',
    duration: '15 min',
    durationMinutes: 15,
    difficulty: 'gentle',
    description: 'Krótki, ale pełen mocy rytuał dla osób, które stały zbyt długo na progu działania. Pomaga przejść od wyobrażeń do pierwszego realnego kroku — bez presji perfekcji, z odwagą niedoskonałego początku.',
    materials: ['Kartka', 'Długopis', 'Stoper (opcjonalnie)'],
    steps: [
      'Napisz na górze kartki: "Chcę zacząć..." i dokończ zdanie. Jeden cel, jeden projekt, jeden krok.',
      'Napisz co blokuje Cię przed pierwszym krokiem. Bądź szczera lub szczery — lęk, brak wiedzy, ocena innych, perfekcjonizm?',
      'Napisz odpowiedź na pytanie: "Jaki byłby absolutnie minimalny, niedoskonały, wystarczający pierwszy krok?"',
      'Ustaw stoper na 10 minut i zrób ten krok teraz. Nawet jeśli będzie to jeden mail, jeden akapit, jeden telefon.',
      'Po 10 minutach wróć do kartki i napisz: "Zacząłem lub zaczęłam. To wystarczy."',
      'Zamknij rytuał głębszym oddechem i zdaniem: "Pierwsza niedoskonała akcja jest ważniejsza niż idealne przygotowanie."',
    ],
    checklist: ['Jeden cel i jeden krok', 'Zidentyfikuj konkretną blokadę', '10 minut realnego działania w rytuale'],
    safetyNote: 'Jeśli blokada jest bardzo głęboka lub wiąże się z lękiem, warto porozmawiać z kimś bliskim lub terapeutą.',
    careNote: 'Najdłuższa podróż zaczyna się od jednego kroku. Ten rytuał to ceremonia pierwszego kroku.',
    idealFor: ['prokrastynacja', 'odkładanie ważnej decyzji', 'lęk przed działaniem'],
    affirmationCategory: 'success',
    bestMoment: 'Rano, gdy dzień jest jeszcze nieobciążony.',
  },
];
